"""Backward-compatibility shim — module moved to lintgate.specification.prescriptive.

This file re-exports all public names from the new location.
Remove this shim once all dependents have been updated.
"""

from lintgate.specification.prescriptive import (  # noqa: F401
    _SPEC_DIR,
    ForbiddenBehavior,
    GenerationConstraint,
    Invariant,
    Predicate,
    PredicateOp,
    PrescriptiveSpec,
    PrescriptiveSpecComposer,
    PrescriptiveWorkflowRecord,
    RefinementObligation,
    ResolvedTarget,
    StateTransition,
    StateVariable,
    TestObligation,
    _build_func_index,
    _find_function_at,
    _match_claims_to_symbols,
    _scan_pspec_stubs,
    _target_hash,
    compile_claim,
    load_all_specs,
    load_spec,
    load_spec_index,
    load_workflow_record,
    pred_and,
    pred_custom,
    pred_eq,
    pred_gt,
    pred_gte,
    pred_lt,
    pred_neq,
    pred_no_raise,
    pred_not,
    pred_or,
    pred_param_count_lte,
    pred_pure,
    pred_raises,
    pred_returns_non_null,
    pred_true,
    pred_type,
    project_claims,
    resolve_targets,
    save_spec,
    save_workflow_record,
    spec_coverage,
)
