#!/usr/bin/env bash
# LintGate Agent Integration — the Symbiote script.
#
# Detects which LLM coding agents are present on this system and generates
# the appropriate config files so each agent auto-discovers LintGate.
#
# Design principle: AGENTS.md is the single source of truth. Every generated
# file either sym-links to it or contains a minimal pointer that says
# "read AGENTS.md." No content is duplicated across agent-specific files.
#
# Usage:
#   bash integrate.sh              # Auto-detect and configure all found agents
#   bash integrate.sh --list       # List detected agents without writing anything
#   bash integrate.sh --clean      # Remove all generated agent config files
#   bash integrate.sh --agent X    # Configure only agent X (claude, cursor, copilot, windsurf, etc.)
#
# Called automatically by setup.sh. Safe to re-run — idempotent.
set -euo pipefail

LINTGATE_DIR="$(cd "$(dirname "$0")" && pwd)"
AGENTS_MD="$LINTGATE_DIR/AGENTS.md"
GENERATED_MARKER="# AUTO-GENERATED by LintGate integrate.sh — do not edit manually."
DRY_RUN=false
LIST_ONLY=false
CLEAN=false
ONLY_AGENT=""

# ── Parse args ────────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case $1 in
        --list)     LIST_ONLY=true; shift ;;
        --clean)    CLEAN=true; shift ;;
        --dry-run)  DRY_RUN=true; shift ;;
        --agent)    ONLY_AGENT="$2"; shift 2 ;;
        *)          echo "Unknown option: $1"; exit 1 ;;
    esac
done

# ── Agent registry ────────────────────────────────────────────────────────
# Each entry: detect function, generate function, cleanup paths
declare -a DETECTED_AGENTS=()
declare -a ALL_GENERATED_FILES=()

log() { echo "  $1"; }
header() { echo ""; echo "=== $1 ==="; }

is_generated() {
    local file="$1"
    [[ -f "$file" ]] && head -1 "$file" 2>/dev/null | grep -q "AUTO-GENERATED by LintGate" && return 0
    [[ -L "$file" ]] && return 0  # sym-links we created
    return 1
}

# ── Pointer file generator ────────────────────────────────────────────────
# Instead of duplicating AGENTS.md content, each agent-specific file is a
# minimal pointer: the marker line + "read AGENTS.md for everything."
generate_pointer() {
    local file="$1"
    local agent_name="$2"
    local extra_notes="${3:-}"

    if [[ "$DRY_RUN" == true ]]; then
        log "[dry-run] Would create $file"
        return
    fi

    mkdir -p "$(dirname "$file")"
    cat > "$file" << POINTER_EOF
$GENERATED_MARKER
# Re-generate with: bash integrate.sh --agent $agent_name
#
# LintGate — Real-time quality supervision for AI-generated code.
#
# This file exists so $agent_name auto-discovers LintGate.
# ALL instructions, tool references, and conventions live in AGENTS.md.
# Read AGENTS.md — it is the single source of truth.
#
# Quick start (if LintGate MCP tools are available):
#   1. build_theory_pack  — orient to the project's theory profile
#   2. controlplane_run   — full supervision mesh
#   3. behavior_precheck  — register predictions before Bash commands
#
# Full tool reference: AGENTS.md (28 tools by cognitive mode)
# Quick orientation: SKILL.md
# Design deep dive: docs/design.md
$extra_notes
POINTER_EOF
    ALL_GENERATED_FILES+=("$file")
    log "Created $file"
}

# ── Cognitive context generator (Tier 2) ──────────────────────────────────
# For agents that support deeper context (not just a pointer), generate
# a starter cognitive context file with dispositions and guardrails adapted
# from the Claude Code experience. These are NOT pointer files — they contain
# real cognitive guidance that helps the agent reason about LintGate.
generate_cognitive_context() {
    local file="$1"
    local agent_name="$2"

    if [[ "$DRY_RUN" == true ]]; then
        log "[dry-run] Would create $file (cognitive context)"
        return
    fi

    # Don't overwrite if user has customized it
    if [[ -f "$file" ]] && ! is_generated "$file"; then
        log "$file exists (user-customized) — not overwriting"
        return
    fi

    mkdir -p "$(dirname "$file")"
    cat > "$file" << 'COGNITIVE_EOF'
# AUTO-GENERATED by LintGate integrate.sh — do not edit manually.
# Re-generate with: bash integrate.sh
# Customize freely — once edited, integrate.sh will not overwrite.
#
# LintGate Cognitive Context
#
# This file teaches you HOW TO THINK when working with LintGate.
# For WHAT TOOLS TO USE, read AGENTS.md.

## Know Your Epistemic State

Before acting on a file you haven't read, before trying a third approach,
before ignoring a behavioral finding — ask yourself:

- **Do I have theory context?** If not → `build_theory_pack`. The theory profile
  tells you what this project values. Without it you are guessing at alignment.
- **What is my prediction accuracy?** If `behavior_precheck` shows accuracy below
  50% after 5+ predictions, your mental model of the project's constraints is wrong.
  Stop and re-orient.
- **What is the coherence state?** If `controlplane_run` shows cross-channel
  disagreement (lint + tests + git pointing at the same files), that convergence
  IS the diagnosis. Read it.

## Dispositions

**When starting a session** — orient first. Call `build_theory_pack` or
`controlplane_status`. The 200 tokens you spend orienting prevent the 2,000
tokens you spend on a doomed approach.

**When acting** — register predictions. Before any Bash command, call
`behavior_precheck` with a structured prediction. This builds the accuracy
signal that modulates behavioral finding confidence.

**When stuck** — DO NOT try variant #4. If you have cycled through 3 approaches,
your problem is not execution — it is understanding. Run `behavior_precheck` to
see your constraint coverage.

**When the system speaks** — findings are weather reports, not commands. But if
you ignore a hard signal and try the same pattern again, the system will escalate.

## Guardrails

- DO NOT disable lint channels globally to hide regressions.
- DO NOT auto-apply generated repairs without explicit acceptance.
- DO NOT try a 4th approach without running `behavior_precheck` first.
- MUST keep hook and MCP outputs machine-readable and stable.
- MUST update AGENTS.md, README.md, and docs/design.md when changing MCP tools.

## References

- Tool reference: AGENTS.md (28 tools by cognitive mode)
- Architecture of Inquiry: .claude/rules/inquiry.md
- Design deep dive: docs/design.md
COGNITIVE_EOF
    ALL_GENERATED_FILES+=("$file")
    log "Created $file (cognitive context — Tier 2)"
}

# ── Agent: Claude Code ────────────────────────────────────────────────────
detect_claude() {
    # Claude Code reads .claude/CLAUDE.md and CLAUDE.md hierarchically
    # It also reads AGENTS.md natively as of 2025
    [[ -d "$HOME/.claude" ]] || command -v claude &>/dev/null
}

generate_claude() {
    # CLAUDE.md is special — it has managed sections for living context,
    # so we DON'T generate or overwrite it. We just verify it exists.
    local claude_md="$LINTGATE_DIR/.claude/CLAUDE.md"
    if [[ -f "$claude_md" ]]; then
        if is_generated "$claude_md"; then
            log "CLAUDE.md is auto-generated — will leave as-is (has managed sections)"
        else
            log "CLAUDE.md exists (hand-maintained with managed sections) — not touching"
        fi
    else
        log "WARNING: .claude/CLAUDE.md missing. Run: bash setup.sh"
    fi
}

clean_claude() {
    # Never clean CLAUDE.md — it has managed sections that accumulate state
    log "CLAUDE.md preserved (has managed sections — never auto-cleaned)"
}

# ── Agent: Cursor ─────────────────────────────────────────────────────────
detect_cursor() {
    # Cursor reads .cursorrules (legacy) and .cursor/rules/*.mdc (current)
    command -v cursor &>/dev/null || [[ -d "$HOME/.cursor" ]] || [[ -d "$HOME/Library/Application Support/Cursor" ]]
}

generate_cursor() {
    # Modern Cursor uses .cursor/rules/*.mdc with YAML frontmatter
    local rules_dir="$LINTGATE_DIR/.cursor/rules"
    local mdc_file="$rules_dir/lintgate.mdc"
    local legacy_file="$LINTGATE_DIR/.cursorrules"

    if [[ "$DRY_RUN" == true ]]; then
        log "[dry-run] Would create $mdc_file and $legacy_file"
        return
    fi

    mkdir -p "$rules_dir"

    # Modern .mdc format with YAML frontmatter
    cat > "$mdc_file" << 'MDC_EOF'
---
description: LintGate quality supervision system
alwaysApply: true
---
# AUTO-GENERATED by LintGate integrate.sh — do not edit manually.
# Re-generate with: bash integrate.sh --agent cursor

Read AGENTS.md for the full LintGate tool reference (28 tools by cognitive mode).
Read SKILL.md for quick orientation. Read docs/design.md for architecture.

Key rules:
- Update AGENTS.md + README.md + docs/design.md when changing MCP tools
- Source of truth: `grep -c "@mcp.tool()" mcp_server.py`
- DO NOT disable lint channels globally
- DO NOT auto-apply repairs without acceptance

If LintGate MCP tools are available, start with:
1. build_theory_pack → 2. controlplane_run → 3. behavior_precheck
MDC_EOF
    ALL_GENERATED_FILES+=("$mdc_file")
    log "Created $mdc_file (modern .mdc format)"

    # Legacy .cursorrules for older Cursor versions
    generate_pointer "$legacy_file" "cursor"
}

clean_cursor() {
    local mdc="$LINTGATE_DIR/.cursor/rules/lintgate.mdc"
    local legacy="$LINTGATE_DIR/.cursorrules"
    for f in "$mdc" "$legacy"; do
        if is_generated "$f"; then
            rm -f "$f"
            log "Removed $f"
        fi
    done
    # Clean up empty .cursor/rules/ dir
    [[ -d "$LINTGATE_DIR/.cursor/rules" ]] && rmdir "$LINTGATE_DIR/.cursor/rules" 2>/dev/null || true
    [[ -d "$LINTGATE_DIR/.cursor" ]] && rmdir "$LINTGATE_DIR/.cursor" 2>/dev/null || true
}

# ── Agent: GitHub Copilot ─────────────────────────────────────────────────
detect_copilot() {
    # Copilot reads .github/copilot-instructions.md
    command -v gh &>/dev/null || [[ -d "$HOME/.config/github-copilot" ]]
}

generate_copilot() {
    generate_pointer "$LINTGATE_DIR/.github/copilot-instructions.md" "copilot"
}

clean_copilot() {
    local f="$LINTGATE_DIR/.github/copilot-instructions.md"
    if is_generated "$f"; then
        rm -f "$f"
        log "Removed $f"
        [[ -d "$LINTGATE_DIR/.github" ]] && rmdir "$LINTGATE_DIR/.github" 2>/dev/null || true
    fi
}

# ── Agent: Windsurf / Codeium ─────────────────────────────────────────────
detect_windsurf() {
    command -v windsurf &>/dev/null || [[ -d "$HOME/.codeium" ]]
}

generate_windsurf() {
    generate_pointer "$LINTGATE_DIR/.windsurfrules" "windsurf"
}

clean_windsurf() {
    local f="$LINTGATE_DIR/.windsurfrules"
    if is_generated "$f"; then rm -f "$f" && log "Removed $f"; fi
}

# ── Agent: Cline ──────────────────────────────────────────────────────────
detect_cline() {
    # Cline reads .clinerules or .clinerules/ directory
    [[ -f "$HOME/.vscode/extensions/"*cline* ]] 2>/dev/null || \
    ls "$HOME/.vscode/extensions/" 2>/dev/null | grep -q "cline" || \
    ls "$HOME/.cursor/extensions/" 2>/dev/null | grep -q "cline"
}

generate_cline() {
    generate_pointer "$LINTGATE_DIR/.clinerules" "cline"
}

clean_cline() {
    local f="$LINTGATE_DIR/.clinerules"
    if is_generated "$f"; then rm -f "$f" && log "Removed $f"; fi
}

# ── Agent: Roo Code ───────────────────────────────────────────────────────
detect_roo() {
    ls "$HOME/.vscode/extensions/" 2>/dev/null | grep -q "roo" || \
    ls "$HOME/.cursor/extensions/" 2>/dev/null | grep -q "roo"
}

generate_roo() {
    local rules_dir="$LINTGATE_DIR/.roo/rules"
    local f="$rules_dir/lintgate.md"
    if [[ "$DRY_RUN" == true ]]; then
        log "[dry-run] Would create $f"
        return
    fi
    mkdir -p "$rules_dir"
    generate_pointer "$f" "roo"
}

clean_roo() {
    local f="$LINTGATE_DIR/.roo/rules/lintgate.md"
    if is_generated "$f"; then
        rm -f "$f"
        log "Removed $f"
        [[ -d "$LINTGATE_DIR/.roo/rules" ]] && rmdir "$LINTGATE_DIR/.roo/rules" 2>/dev/null || true
        [[ -d "$LINTGATE_DIR/.roo" ]] && rmdir "$LINTGATE_DIR/.roo" 2>/dev/null || true
    fi
}

# ── Agent: Gemini CLI ─────────────────────────────────────────────────────
detect_gemini() {
    command -v gemini &>/dev/null || [[ -d "$HOME/.gemini" ]]
}

generate_gemini() {
    # Gemini CLI supports hierarchical GEMINI.md — give it Tier 2 cognitive context
    generate_cognitive_context "$LINTGATE_DIR/GEMINI.md" "gemini"
}

clean_gemini() {
    local f="$LINTGATE_DIR/GEMINI.md"
    if is_generated "$f"; then rm -f "$f" && log "Removed $f"; fi
}

# ── Agent: Aider ──────────────────────────────────────────────────────────
detect_aider() {
    command -v aider &>/dev/null || [[ -f "$HOME/.aider.conf.yml" ]]
}

generate_aider() {
    # Aider uses CONVENTIONS.md loaded via config
    generate_pointer "$LINTGATE_DIR/CONVENTIONS.md" "aider" \
        "# Aider: load this with --read CONVENTIONS.md or add to .aider.conf.yml"
}

clean_aider() {
    local f="$LINTGATE_DIR/CONVENTIONS.md"
    if is_generated "$f"; then rm -f "$f" && log "Removed $f"; fi
}

# ── Agent: Amazon Q ───────────────────────────────────────────────────────
detect_amazonq() {
    command -v q &>/dev/null || [[ -d "$HOME/.aws/amazonq" ]]
}

generate_amazonq() {
    local rules_dir="$LINTGATE_DIR/.amazonq/rules"
    local f="$rules_dir/lintgate.md"
    if [[ "$DRY_RUN" == true ]]; then
        log "[dry-run] Would create $f"
        return
    fi
    mkdir -p "$rules_dir"
    generate_pointer "$f" "amazonq"
}

clean_amazonq() {
    local f="$LINTGATE_DIR/.amazonq/rules/lintgate.md"
    if is_generated "$f"; then
        rm -f "$f"
        log "Removed $f"
        [[ -d "$LINTGATE_DIR/.amazonq/rules" ]] && rmdir "$LINTGATE_DIR/.amazonq/rules" 2>/dev/null || true
        [[ -d "$LINTGATE_DIR/.amazonq" ]] && rmdir "$LINTGATE_DIR/.amazonq" 2>/dev/null || true
    fi
}

# ── Agent: Google Gemini (Antigravity format) ──────────────────────────────
detect_antigravity() {
    # Google's Antigravity/AI Studio format — .gai or similar conventions
    # Detect via Google AI Studio CLI or Gemini API key presence
    [[ -n "${GOOGLE_API_KEY:-}" ]] || [[ -f "$HOME/.config/google-ai-studio/config" ]]
}

generate_antigravity() {
    generate_pointer "$LINTGATE_DIR/.gai-instructions.md" "antigravity" \
        "# Google AI Studio / Antigravity format"
}

clean_antigravity() {
    local f="$LINTGATE_DIR/.gai-instructions.md"
    if is_generated "$f"; then rm -f "$f" && log "Removed $f"; fi
}

# ── Agent: Codex / ChatGPT (Tier 2) ──────────────────────────────────────
detect_codex() {
    # Codex CLI reads AGENTS.md natively, supports MCP via .codex/config.toml
    command -v codex &>/dev/null || [[ -d "$HOME/.codex" ]] || [[ -n "${OPENAI_API_KEY:-}" ]]
}

generate_codex() {
    # Codex reads AGENTS.md natively — no pointer needed for tool reference.
    # But we generate a cognitive context file for Tier 2 depth.
    generate_cognitive_context "$LINTGATE_DIR/.codex/context.md" "codex"
}

clean_codex() {
    local f="$LINTGATE_DIR/.codex/context.md"
    if is_generated "$f"; then
        rm -f "$f"
        log "Removed $f"
        [[ -d "$LINTGATE_DIR/.codex" ]] && rmdir "$LINTGATE_DIR/.codex" 2>/dev/null || true
    fi
}

# ── Master agent table ────────────────────────────────────────────────────
declare -A AGENTS=(
    [claude]="detect_claude:generate_claude:clean_claude"
    [codex]="detect_codex:generate_codex:clean_codex"
    [cursor]="detect_cursor:generate_cursor:clean_cursor"
    [copilot]="detect_copilot:generate_copilot:clean_copilot"
    [windsurf]="detect_windsurf:generate_windsurf:clean_windsurf"
    [cline]="detect_cline:generate_cline:clean_cline"
    [roo]="detect_roo:generate_roo:clean_roo"
    [gemini]="detect_gemini:generate_gemini:clean_gemini"
    [aider]="detect_aider:generate_aider:clean_aider"
    [amazonq]="detect_amazonq:generate_amazonq:clean_amazonq"
    [antigravity]="detect_antigravity:generate_antigravity:clean_antigravity"
)

# ── Run ───────────────────────────────────────────────────────────────────
header "LintGate Agent Integration"

if [[ "$CLEAN" == true ]]; then
    echo "Cleaning generated agent config files..."
    for agent in "${!AGENTS[@]}"; do
        IFS=':' read -r _ _ clean_fn <<< "${AGENTS[$agent]}"
        $clean_fn
    done
    echo ""
    echo "Done. AGENTS.md and .claude/CLAUDE.md preserved."
    exit 0
fi

# Detect
echo "Scanning for LLM coding agents..."
for agent in $(echo "${!AGENTS[@]}" | tr ' ' '\n' | sort); do
    IFS=':' read -r detect_fn _ _ <<< "${AGENTS[$agent]}"
    if $detect_fn 2>/dev/null; then
        DETECTED_AGENTS+=("$agent")
        log "Found: $agent"
    fi
done

if [[ ${#DETECTED_AGENTS[@]} -eq 0 ]]; then
    echo ""
    echo "No agents detected. AGENTS.md is still readable by any agent."
    echo "Re-run after installing a coding agent, or use --agent NAME to force."
    exit 0
fi

if [[ "$LIST_ONLY" == true ]]; then
    echo ""
    echo "Detected agents: ${DETECTED_AGENTS[*]}"
    echo "Run without --list to generate config files."
    exit 0
fi

# Generate
echo ""
echo "Generating agent config files..."
if [[ -n "$ONLY_AGENT" ]]; then
    if [[ -v "AGENTS[${ONLY_AGENT}]" ]]; then
        IFS=':' read -r _ gen_fn _ <<< "${AGENTS[$ONLY_AGENT]}"
        $gen_fn
    else
        echo "Unknown agent: $ONLY_AGENT"
        echo "Known agents: ${!AGENTS[*]}"
        exit 1
    fi
else
    for agent in "${DETECTED_AGENTS[@]}"; do
        IFS=':' read -r _ gen_fn _ <<< "${AGENTS[$agent]}"
        $gen_fn
    done
fi

# Summary
echo ""
header "Integration Complete"
echo ""
echo "Detected agents:  ${DETECTED_AGENTS[*]}"
echo "Generated files:  ${#ALL_GENERATED_FILES[@]}"
echo "Source of truth:   AGENTS.md"
echo ""
echo "Every generated file is a pointer to AGENTS.md."
echo "To update instructions, edit AGENTS.md — all agents read it."
echo "To regenerate: bash integrate.sh"
echo "To clean up:   bash integrate.sh --clean"
