"""Rules and configuration generation helpers."""

from __future__ import annotations

import re
from typing import Any


def _generate_codeclimate_yml(layout: dict[str, Any]) -> str:
    """Generate a tailored .codeclimate.yml."""
    excludes = list(layout.get("exclude_patterns", []))
    # De-duplicate
    seen: set[str] = set()
    unique_excludes: list[str] = []
    for e in excludes:
        if e not in seen:
            seen.add(e)
            unique_excludes.append(e)

    lines = [
        'version: "2"',
        "",
        "checks:",
        "  method-complexity:",
        "    enabled: true",
        "    config:",
        "      threshold: 20",
        "",
        "  file-lines:",
        "    enabled: true",
        "    config:",
        "      threshold: 500",
        "",
        "  method-lines:",
        "    enabled: true",
        "    config:",
        "      threshold: 100",
        "",
        "  method-count:",
        "    enabled: true",
        "    config:",
        "      threshold: 30",
        "",
        "  return-statements:",
        "    enabled: true",
        "    config:",
        "      threshold: 8",
        "",
        "  argument-count:",
        "    enabled: true",
        "    config:",
        "      threshold: 8",
        "",
        "  identical-code:",
        "    enabled: true",
        "    config:",
        "      threshold: 3",
        "",
        "  similar-code:",
        "    enabled: true",
        "    config:",
        "      threshold: 3",
        "",
        "plugins:",
        "  radon:",
        "    enabled: true",
        "    config:",
        '      threshold: "C"',
        "",
        "  duplication:",
        "    enabled: true",
        "    config:",
        "      languages:",
        "        python:",
        "          mass_threshold: 40",
        "",
        "exclude_patterns:",
    ]
    for pattern in unique_excludes:
        lines.append(f'  - "{pattern}"')

    return "\n".join(lines) + "\n"


def _generate_sonar_properties(github: dict[str, Any], layout: dict[str, Any]) -> str:
    """Generate a tailored sonar-project.properties."""
    owner = github.get("owner", "OWNER")
    repo = github.get("repo", "REPO")
    # SonarCloud keys: alphanumeric, _, -, .
    project_key = re.sub(r"[^a-zA-Z0-9_.\-]", "_", f"{owner}_{repo}")

    source_dirs = ",".join(layout.get("source_dirs", ["."]))
    test_dirs = ",".join(layout.get("test_dirs", ["tests"]))
    python_version = layout.get("python_version", "3")

    exclude_parts = list(layout.get("exclude_patterns", []))
    # Shell scripts are not Python — SonarCloud's Python analyzer misclassifies them
    if "*.sh" not in exclude_parts:
        exclude_parts.append("*.sh")
    exclusions = ",\\\n  ".join(
        p
        if (p.endswith("**") or p.endswith("**/*") or p.startswith("*."))
        else f"{p}**"
        for p in exclude_parts
    )

    lines = [
        "# SonarCloud configuration — generated by LintGate setup_github_quality",
        f"sonar.projectKey={project_key}",
        f"sonar.organization={owner}",
        f"sonar.projectName={repo}",
        "",
        "# Source layout",
        f"sonar.sources={source_dirs}",
        f"sonar.tests={test_dirs}",
        f"sonar.python.version={python_version}",
        "",
        "# Exclusions",
        "sonar.exclusions=\\",
        f"  {exclusions}",
        "",
        "# Coverage (generate with: pytest --cov --cov-report=xml)",
        "sonar.python.coverage.reportPaths=coverage.xml",
        "# sonar.coverage.exclusions=\\",
        "#   path/to/wip_module.py,\\",
        "#   path/to/experimental/**",
        "",
        "# Tolerated false positives — LintGate is a local CLI tool;",
        "# all path inputs come from the local filesystem or agent hook stdin,",
        "# not from HTTP/network input. Regex inputs from local files only.",
        "sonar.issue.ignore.multicriteria=fp1,fp2,fp3",
        "sonar.issue.ignore.multicriteria.fp1.ruleKey=pythonsecurity:S2083",
        "sonar.issue.ignore.multicriteria.fp1.resourceKey=**/*.py",
        "sonar.issue.ignore.multicriteria.fp2.ruleKey=python:S5852",
        "sonar.issue.ignore.multicriteria.fp2.resourceKey=**/*.py",
        "sonar.issue.ignore.multicriteria.fp3.ruleKey=pythonsecurity:S6549",
        "sonar.issue.ignore.multicriteria.fp3.resourceKey=**/*.py",
    ]
    return "\n".join(lines) + "\n"


def _generate_coveragerc() -> str:
    """Generate a baseline .coveragerc aligned with CI coverage workflows."""
    lines = [
        "[run]",
        "source =",
        "    lintgate",
        "    mcp_tools",
        "omit =",
        "    */pytest-*/*/repo/lintgate/*",
        "    lintgate/hook_posttooluse.py",
    ]
    return "\n".join(lines) + "\n"


def _generate_gitleaks_toml() -> str:
    """Generate a baseline gitleaks config (extends defaults)."""
    lines = [
        'title = "Gitleaks baseline configuration"',
        "",
        "[extend]",
        "useDefault = true",
        "",
        "# Add project-specific allowlists as needed, for example:",
        "# [allowlist]",
        '# description = "Intentional fixture in tests"',
        "# paths = [",
        "#   '''tests/test_secret_fixture\\.py'''",
        "# ]",
    ]
    return "\n".join(lines) + "\n"


def _generate_security_md(github: dict[str, Any]) -> str:
    """Generate SECURITY.md with responsible disclosure policy.

    Args:
        github: Dict with 'owner' and 'repo' keys from _detect_github_remote.
    """
    owner = github.get("owner", "OWNER")
    repo = github.get("repo", "REPO")

    lines = [
        "# Security Policy",
        "",
        "## Reporting a Vulnerability",
        "",
        "If you discover a security vulnerability in this project, please report it",
        "responsibly. **Do not open a public issue.**",
        "",
        "### Preferred Method",
        "",
        f"Use [GitHub Security Advisories](https://github.com/{owner}/{repo}"
        "/security/advisories/new) to report vulnerabilities privately.",
        "",
        "### What to Include",
        "",
        "- Description of the vulnerability",
        "- Steps to reproduce",
        "- Potential impact",
        "- Suggested fix (if any)",
        "",
        "### Response Timeline",
        "",
        "- **Acknowledgment**: Within 48 hours",
        "- **Assessment**: Within 7 days",
        "- **Fix timeline**: Depends on severity; critical issues prioritized",
        "",
        "## Supported Versions",
        "",
        "Security updates are applied to the latest release on the default branch.",
        "",
        "## Security Tools",
        "",
        "This project uses automated security scanning:",
        "- **gitleaks** — secrets detection in commits",
        "- **Bandit** — Python SAST analysis",
        "- **pip-audit** — supply chain vulnerability scanning",
        "- **OpenSSF Scorecard** — project security posture assessment",
        "",
        "---",
        "",
        "*Generated by [LintGate](https://github.com/rohanvinaik/LintGate)*",
    ]
    return "\n".join(lines) + "\n"


def _generate_dependabot_yml() -> str:
    """Generate Dependabot configuration for automated dependency updates.

    Configures weekly updates for pip (Python) and GitHub Actions ecosystems.
    """
    lines = [
        "# Dependabot configuration — generated by LintGate",
        "version: 2",
        "updates:",
        "  - package-ecosystem: pip",
        "    directory: /",
        "    schedule:",
        "      interval: weekly",
        "    open-pull-requests-limit: 10",
        "    labels:",
        "      - dependencies",
        "",
        "  - package-ecosystem: github-actions",
        "    directory: /",
        "    schedule:",
        "      interval: weekly",
        "    open-pull-requests-limit: 5",
        "    labels:",
        "      - dependencies",
        "      - ci",
    ]
    return "\n".join(lines) + "\n"


def _normalize_qlty_exclude_pattern(pattern: str) -> str:
    """Normalize qlty exclude pattern without corrupting wildcard file globs."""
    pat = pattern.strip()
    if not pat:
        return ""
    if pat.endswith("/**"):
        return pat
    if pat.endswith("/"):
        return f"{pat}**"
    if any(ch in pat for ch in "*?[]"):
        return pat
    return f"{pat}/**"
