"""Workflow generation helpers."""

from __future__ import annotations

# Constants used by both this module and quality_helpers / onboarding_tools.
# Defined here (the primary consumer) to avoid an import cycle with quality_helpers.
REQUIRED_ARTIFACTS = {
    "codeclimate": ".codeclimate.yml",
    "sonar": "sonar-project.properties",
    "coveragerc": ".coveragerc",
    "gitleaks": ".gitleaks.toml",
    "security_policy": "SECURITY.md",
}

REQUIRED_BADGE_FINGERPRINTS = [
    "actions/workflows/tests.yml/badge.svg",
    "actions/workflows/security-lite.yml/badge.svg",
    "metric=alert_status",
    "metric=coverage",
    "metric=security_rating",
]


def _generate_scorecard_workflow() -> str:
    """Generate OpenSSF Scorecard GitHub Action workflow."""
    lines = [
        "name: OpenSSF Scorecard",
        "",
        "on:",
        "  branch_protection_rule:",
        "  schedule:",
        "    - cron: '30 1 * * 1'  # Weekly Monday 01:30 UTC",
        "  push:",
        "    branches: [main, master]",
        "  workflow_dispatch:",
        "",
        "permissions: read-all",
        "",
        "jobs:",
        "  analysis:",
        "    name: Scorecard Analysis",
        "    runs-on: ubuntu-latest",
        "    permissions:",
        "      security-events: write",
        "      id-token: write",
        "    steps:",
        "      - name: Checkout",
        "        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4",
        "        with:",
        "          persist-credentials: false",
        "",
        "      - name: Run Scorecard",
        "        uses: ossf/scorecard-action@62b2cac7ed8198b15735ed49ab1e5cf35480ba46 # v2.4.0",
        "        with:",
        "          results_file: results.sarif",
        "          results_format: sarif",
        "          publish_results: true",
        "",
        "      - name: Upload SARIF",
        "        uses: github/codeql-action/upload-sarif@45580472a5bb82c4681c4ac726cfdb60060c2ee1 # v3",
        "        with:",
        "          sarif_file: results.sarif",
        "",
    ]
    return "\n".join(lines) + "\n"


def _generate_codeql_workflow() -> str:
    """Generate a CodeQL analysis workflow."""
    lines = [
        "name: CodeQL",
        "",
        "on:",
        "  push:",
        "  pull_request:",
        "    types: [opened, synchronize, reopened]",
        "  schedule:",
        "    - cron: '15 3 * * 1'  # Weekly Monday 03:15 UTC",
        "",
        "permissions:",
        "  contents: read",
        "  security-events: write",
        "",
        "concurrency:",
        "  group: codeql-${{ github.workflow }}-${{ github.ref }}",
        "  cancel-in-progress: true",
        "",
        "jobs:",
        "  analyze:",
        "    name: CodeQL Analysis",
        "    runs-on: ubuntu-latest",
        "    steps:",
        "      - name: Checkout",
        "        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4",
        "",
        "      - name: Initialize CodeQL",
        "        uses: github/codeql-action/init@45580472a5bb82c4681c4ac726cfdb60060c2ee1 # v3",
        "        with:",
        "          languages: python",
        "",
        "      - name: Autobuild",
        "        uses: github/codeql-action/autobuild@45580472a5bb82c4681c4ac726cfdb60060c2ee1 # v3",
        "",
        "      - name: Perform CodeQL Analysis",
        "        uses: github/codeql-action/analyze@45580472a5bb82c4681c4ac726cfdb60060c2ee1 # v3",
    ]
    return "\n".join(lines) + "\n"


def _generate_clusterfuzzlite_workflow() -> str:
    """Generate a ClusterFuzzLite batch fuzzing workflow."""
    lines = [
        "name: ClusterFuzzLite",
        "",
        "on:",
        "  push:",
        "    branches: [main]",
        "  pull_request:",
        "    branches: [main]",
        "  schedule:",
        "    - cron: '0 6 * * 0'  # Weekly Sunday 06:00 UTC (batch mode)",
        "  workflow_dispatch:",
        "",
        "permissions:",
        "  contents: read",
        "  security-events: write",
        "",
        "concurrency:",
        "  group: cif-${{ github.workflow }}-${{ github.ref }}",
        "  cancel-in-progress: true",
        "",
        "jobs:",
        "  fuzz:",
        "    name: ClusterFuzzLite Batch Fuzzing",
        "    runs-on: ubuntu-latest",
        "    steps:",
        "      - name: Checkout",
        "        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4",
        "",
        "      - name: Build fuzzers",
        "        id: build",
        "        uses: google/clusterfuzzlite/actions/build_fuzzers@52ecc61cb587ee99c26825a112a21abf19c7448c # main",
        "        with:",
        "          language: python",
        "",
        "      - name: Run fuzzers",
        "        id: run",
        "        uses: google/clusterfuzzlite/actions/run_fuzzers@52ecc61cb587ee99c26825a112a21abf19c7448c # main",
        "        with:",
        "          github-token: ${{ secrets.GITHUB_TOKEN }}",
        "          fuzz-seconds: 300",
        "          mode: batch",
    ]
    return "\n".join(lines) + "\n"


def _generate_pypi_publish_workflow() -> str:
    """Generate a PyPI publish workflow."""
    lines = [
        "name: Publish to PyPI",
        "",
        "on:",
        "  release:",
        "    types: [published]",
        "  workflow_dispatch:",
        "",
        "permissions:",
        "  contents: read",
        "",
        "jobs:",
        "  build:",
        "    name: Build distribution",
        "    runs-on: ubuntu-latest",
        "    steps:",
        "      - name: Checkout",
        "        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4",
        "",
        "      - name: Set up Python",
        "        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5",
        "        with:",
        '          python-version: "3.11"',
        "",
        "      - name: Install build tools",
        "        run: python -m pip install --upgrade pip==25.0.1 build",
        "",
        "      - name: Build sdist and wheel",
        "        run: python -m build",
        "",
        "      - name: Upload dist artifacts",
        "        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4",
        "        with:",
        "          name: dist",
        "          path: dist/",
        "",
        "  publish:",
        "    name: Publish to PyPI",
        "    needs: build",
        "    runs-on: ubuntu-latest",
        "    environment: pypi",
        "    permissions:",
        "      id-token: write",
        "    steps:",
        "      - name: Download dist artifacts",
        "        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4",
        "        with:",
        "          name: dist",
        "          path: dist/",
        "",
        "      - name: Publish to PyPI (trusted publisher)",
        "        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # release/v1",
        "",
        "  sign:",
        "    name: Sign with Sigstore",
        "    needs: publish",
        "    runs-on: ubuntu-latest",
        "    permissions:",
        "      id-token: write",
        "      contents: read",
        "    steps:",
        "      - name: Download dist artifacts",
        "        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4",
        "        with:",
        "          name: dist",
        "          path: dist/",
        "",
        "      - name: Sign with Sigstore",
        "        uses: sigstore/gh-action-sigstore-python@a5caf349bc536fbef3668a10ed7f5cd309a4b53d # v3.2.0",
        "        with:",
        "          inputs: dist/*.tar.gz dist/*.whl",
        "",
        "      - name: Upload signatures",
        "        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4",
        "        with:",
        "          name: signatures",
        "          path: dist/*.sigstore.json",
        "",
    ]
    return "\n".join(lines) + "\n"


def _generate_quality_infra_gate_workflow() -> str:
    """Generate the quality infrastructure gate CI workflow."""
    file_checks: list[str] = []
    for _name, rel_path in REQUIRED_ARTIFACTS.items():
        file_checks.append(
            f'          if [ ! -e "{rel_path}" ]; then '
            f'echo "MISSING: {rel_path}"; MISSING=$((MISSING+1)); fi'
        )

    fp_checks: list[str] = []
    for fp in REQUIRED_BADGE_FINGERPRINTS:
        escaped = fp.replace(".", "\\.").replace("/", "\\/")
        fp_checks.append(
            f'          if ! grep -q "{escaped}" README.md 2>/dev/null; then '
            f'echo "BADGE MISSING: {fp}"; MISSING=$((MISSING+1)); fi'
        )

    lines = [
        "name: Quality Infrastructure Gate",
        "",
        "on:",
        "  push:",
        "  pull_request:",
        "    types: [opened, synchronize, reopened]",
        "  workflow_dispatch:",
        "",
        "permissions:",
        "  contents: read",
        "",
        "concurrency:",
        "  group: quality-infra-${{ github.workflow }}-${{ github.ref }}",
        "  cancel-in-progress: true",
        "",
        "jobs:",
        "  gate:",
        "    name: Quality Infrastructure Gate",
        "    runs-on: ubuntu-latest",
        "    steps:",
        "      - name: Checkout",
        "        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4",
        "",
        "      - name: Check quality infrastructure completeness",
        "        run: |",
        "          MISSING=0",
        *file_checks,
        *fp_checks,
        '          if [ "$MISSING" -gt 0 ]; then',
        '            echo ""',
        '            echo "Quality infrastructure is incomplete ($MISSING items missing)."',
        '            echo "Fix: run setup_github_quality(path=..., write=True)"',
        "            exit 1",
        "          fi",
        '          echo "Quality infrastructure: complete"',
    ]
    return "\n".join(lines) + "\n"


def _generate_qlty_workflow() -> str:
    """Generate a GitHub Actions workflow for qlty checks."""
    lines = [
        "name: Qlty Analysis",
        "",
        "on:",
        "  push:",
        "  pull_request:",
        "    types: [opened, synchronize, reopened]",
        "  workflow_dispatch:",
        "",
        "permissions:",
        "  contents: read",
        "",
        "concurrency:",
        "  group: qlty-${{ github.workflow }}-${{ github.ref }}",
        "  cancel-in-progress: true",
        "",
        "jobs:",
        "  qlty:",
        "    name: Qlty Check",
        "    runs-on: ubuntu-latest",
        "    steps:",
        "      - name: Checkout",
        "        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4",
        "",
        "      - name: Install qlty",
        "        uses: qltysh/qlty-action/install@0814173ae3b13074fc896ca0e8e6d631c8352509 # main",
        "",
        "      - name: Initialize qlty (if needed)",
        "        run: |",
        "          if ! qlty check --all --dry-run >/dev/null 2>&1; then",
        "            qlty init --skip-plugins 2>/dev/null || true",
        "          fi",
        "",
        "      - name: Run qlty checks",
        "        run: qlty check --all",
    ]
    return "\n".join(lines) + "\n"


def _generate_security_workflow() -> str:
    """Generate a lightweight security scanning workflow."""
    lines = [
        "name: Security Lite",
        "",
        "on:",
        "  push:",
        "  pull_request:",
        "    types: [opened, synchronize, reopened]",
        "  workflow_dispatch:",
        "",
        "permissions:",
        "  contents: read",
        "  security-events: write",
        "",
        "concurrency:",
        "  group: security-lite-${{ github.workflow }}-${{ github.ref }}",
        "  cancel-in-progress: true",
        "",
        "jobs:",
        "  security:",
        "    name: Security Scanning",
        "    runs-on: ubuntu-latest",
        "    steps:",
        "      - name: Checkout",
        "        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4",
        "",
        "      - name: Set up Python",
        "        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5",
        "        with:",
        '          python-version: "3.11"',
        "",
        "      - name: Install Bandit",
        "        run: pip install bandit",
        "",
        "      - name: Run Bandit",
        "        run: bandit -r . -ll -ii",
        "",
        "      - name: Run pip-audit",
        "        uses: pypa/gh-action-pip-audit@v1.0.8",
        "        with:",
        "          inputs: requirements.txt",
    ]
    return "\n".join(lines) + "\n"


def _generate_tests_workflow() -> str:
    """Generate a comprehensive test workflow with coverage."""
    lines = [
        "name: tests",
        "",
        "on:",
        "  push:",
        "    branches: [main, master]",
        "  pull_request:",
        "    branches: [main, master]",
        "  workflow_dispatch:",
        "",
        "permissions:",
        "  contents: read",
        "",
        "jobs:",
        "  test:",
        "    name: Run tests",
        "    runs-on: ubuntu-latest",
        "    steps:",
        "      - name: Checkout",
        "        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4",
        "",
        "      - name: Set up Python",
        "        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5",
        "        with:",
        '          python-version: "3.11"',
        "",
        "      - name: Install dependencies",
        "        run: |",
        "          python -m pip install --upgrade pip",
        "          pip install pytest pytest-cov",
        "          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi",
        "",
        "      - name: Run tests with coverage",
        "        run: pytest --cov=./ --cov-report=xml",
        "",
        "      - name: Upload coverage to SonarCloud",
        "        uses: sonarsource/sonarcloud-github-action@v2",
        "        env:",
        "          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}",
        "          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}",
    ]
    return "\n".join(lines) + "\n"
