"""Characterization test for _compute_dependency_tiers.

Auto-generated by test_characterize. Maturity: unchecked.
"""

from __future__ import annotations

from lintgate.controlplane.work_queue import _compute_dependency_tiers


def test__compute_dependency_tiers_characterization():
    """Characterization: capture current behavior of _compute_dependency_tiers."""
    import_graph: dict[str, list[str] | set[str]] = {}
    project_modules: set[str] = set()

    result = _compute_dependency_tiers(import_graph, project_modules)

    assert result is not None
