"""Tests for mcp_tools/_gh_wiki_impl.py — wiki page rendering, collection, and sync."""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any
from unittest.mock import MagicMock, patch

import pytest

from mcp_tools._gh_wiki_impl import (
    _collect_compass_pages,
    _collect_design_pages,
    _collect_pages,
    _collect_theory_pages,
    _flush_section,
    _read_remote_wiki_page,
    _render_compass_axis,
    _render_compass_wiki_page,
    _render_theory_wiki_page,
    _split_design_md,
    _write_and_push_pages,
    impl_project_wiki_read,
    impl_project_wiki_sync,
)


# ── _render_theory_wiki_page ─────────────────────────────────────────


class TestRenderTheoryWikiPage:
    def test_empty_facets(self):
        result = _render_theory_wiki_page({"facets": {}})
        assert "No theory profile extracted yet." in result
        assert "# Theory Profile" in result

    def test_no_facets_key(self):
        result = _render_theory_wiki_page({})
        assert "No theory profile extracted yet." in result

    def test_facets_with_list_claims(self):
        theory = {
            "facets": {
                "core_theory": [
                    {"text": "Claim one"},
                    {"text": "Claim two"},
                ],
            },
        }
        result = _render_theory_wiki_page(theory)
        assert "## Core Theory" in result
        assert "- Claim one" in result
        assert "- Claim two" in result

    def test_facets_with_dict_claims(self):
        theory = {
            "facets": {
                "problem_solving": {
                    "claims": [{"text": "Solve incrementally"}],
                },
            },
        }
        result = _render_theory_wiki_page(theory)
        assert "## Problem Solving" in result
        assert "- Solve incrementally" in result

    def test_facet_with_empty_claims(self):
        theory: dict[str, Any] = {"facets": {"alignment": {"claims": []}}}
        result = _render_theory_wiki_page(theory)
        assert "_No claims extracted._" in result

    def test_claims_truncated_at_20(self):
        claims = [{"text": f"Claim {i}"} for i in range(25)]
        theory = {"facets": {"big_facet": claims}}
        result = _render_theory_wiki_page(theory)
        assert "- Claim 19" in result
        assert "- Claim 20" not in result

    def test_string_claims(self):
        theory = {"facets": {"simple": ["plain string claim"]}}
        result = _render_theory_wiki_page(theory)
        assert "- plain string claim" in result

    def test_header_line(self):
        result = _render_theory_wiki_page({"facets": {}})
        assert result.startswith("_Auto-generated by LintGate")


# ── _render_compass_wiki_page ────────────────────────────────────────


class TestRenderCompassWikiPage:
    def test_empty_axes(self):
        result = _render_compass_wiki_page({"axes": {}})
        assert "No compass data available yet." in result
        assert "# Project Compass" in result

    def test_no_axes_key(self):
        result = _render_compass_wiki_page({})
        assert "No compass data available yet." in result

    def test_axes_with_dict_data(self):
        compass = {
            "axes": {
                "code_quality": {
                    "depth": "deep",
                    "toward": ["Clean code"],
                    "away": ["Spaghetti"],
                    "forbidden": ["Copy-paste"],
                },
            },
        }
        result = _render_compass_wiki_page(compass)
        assert "## Code Quality" in result
        assert "**Depth**: deep" in result
        assert "### Toward" in result
        assert "- Clean code" in result
        assert "### Away" in result
        assert "- Spaghetti" in result
        assert "### Forbidden" in result
        assert "- Copy-paste" in result

    def test_axes_with_non_dict_data(self):
        compass = {"axes": {"simple_axis": "just a string value"}}
        result = _render_compass_wiki_page(compass)
        assert "## Simple Axis" in result
        assert "just a string value" in result

    def test_header_line(self):
        result = _render_compass_wiki_page({"axes": {}})
        assert result.startswith("_Auto-generated by LintGate")


# ── _render_compass_axis ─────────────────────────────────────────────


class TestRenderCompassAxis:
    def test_full_axis(self):
        lines: list[str] = []
        axis_data = {
            "depth": "moderate",
            "toward": ["A", "B"],
            "away": ["C"],
            "forbidden": ["D"],
        }
        _render_compass_axis(lines, axis_data)
        assert "**Depth**: moderate" in lines
        assert "### Toward" in lines
        assert "- A" in lines
        assert "- B" in lines
        assert "### Away" in lines
        assert "- C" in lines
        assert "### Forbidden" in lines
        assert "- D" in lines

    def test_missing_depth_defaults_unknown(self):
        lines: list[str] = []
        _render_compass_axis(lines, {})
        assert "**Depth**: unknown" in lines

    def test_empty_sections_omitted(self):
        lines: list[str] = []
        _render_compass_axis(lines, {"depth": "shallow", "toward": [], "away": [], "forbidden": []})
        assert "### Toward" not in lines
        assert "### Away" not in lines
        assert "### Forbidden" not in lines

    def test_partial_sections(self):
        lines: list[str] = []
        _render_compass_axis(lines, {"depth": "x", "toward": ["yes"], "away": [], "forbidden": []})
        assert "### Toward" in lines
        assert "- yes" in lines
        assert "### Away" not in lines


# ── _split_design_md ─────────────────────────────────────────────────


class TestSplitDesignMd:
    def test_splits_by_h2_headings(self, tmp_path):
        content = "# Title\n\n## Architecture\n\n" + ("x" * 250) + "\n\n## Config\n\n" + ("y" * 250)
        p = tmp_path / "design.md"
        p.write_text(content)
        pages = _split_design_md(str(p))
        assert "Architecture" in pages
        assert "Config" in pages
        assert pages["Architecture"].startswith("# Architecture")
        assert pages["Config"].startswith("# Config")

    def test_skips_short_sections(self, tmp_path):
        content = "## Short\n\nToo short\n\n## Long\n\n" + ("x" * 250)
        p = tmp_path / "design.md"
        p.write_text(content)
        pages = _split_design_md(str(p))
        assert "Short" not in pages
        assert "Long" in pages

    def test_nonexistent_file(self):
        pages = _split_design_md("/nonexistent/design.md")
        assert pages == {}

    def test_heading_slug_strips_special_chars(self, tmp_path):
        content = "## My Cool Section! (v2)\n\n" + ("x" * 250)
        p = tmp_path / "design.md"
        p.write_text(content)
        pages = _split_design_md(str(p))
        assert "My-Cool-Section-v2" in pages


# ── _flush_section ───────────────────────────────────────────────────


class TestFlushSection:
    def test_flushes_long_section(self):
        pages: dict[str, str] = {}
        lines = ["x" * 250]
        _flush_section(pages, "Title", lines)
        assert "Title" in pages
        assert pages["Title"].startswith("# Title")

    def test_skips_short_section(self):
        pages: dict[str, str] = {}
        _flush_section(pages, "Title", ["short"])
        assert pages == {}

    def test_none_heading_skipped(self):
        pages: dict[str, str] = {}
        _flush_section(pages, None, ["x" * 300])
        assert pages == {}

    def test_slug_generation(self):
        pages: dict[str, str] = {}
        _flush_section(pages, "My Heading!!", ["x" * 250])
        assert "My-Heading" in pages


# ── _collect_theory_pages ────────────────────────────────────────────


class TestCollectTheoryPages:
    @patch("lintgate.theory_extractor.extract_theory")
    def test_success(self, mock_extract):
        mock_extract.return_value = {"facets": {"core": [{"text": "A"}]}}
        pages = _collect_theory_pages("/fake/path")
        assert "Theory-Profile" in pages
        assert "# Theory Profile" in pages["Theory-Profile"]
        assert "- A" in pages["Theory-Profile"]

    @patch("lintgate.theory_extractor.extract_theory", side_effect=RuntimeError("boom"))
    def test_error_captured(self, mock_extract):
        pages = _collect_theory_pages("/fake/path")
        assert "Theory-Profile" in pages
        assert "Error extracting theory" in pages["Theory-Profile"]


# ── _collect_compass_pages ───────────────────────────────────────────


class TestCollectCompassPages:
    def test_compass_exists(self, tmp_path):
        compass_dir = tmp_path / ".claude"
        compass_dir.mkdir()
        compass_file = compass_dir / "compass.json"
        compass_data = {"axes": {"quality": {"depth": "deep", "toward": ["tests"]}}}
        compass_file.write_text(json.dumps(compass_data))
        pages = _collect_compass_pages(str(tmp_path))
        assert "Theory-Compass" in pages
        assert "# Project Compass" in pages["Theory-Compass"]
        assert "Quality" in pages["Theory-Compass"]

    def test_compass_missing(self, tmp_path):
        pages = _collect_compass_pages(str(tmp_path))
        assert "Theory-Compass" in pages
        assert "No compass data available" in pages["Theory-Compass"]
        assert "compass_update" in pages["Theory-Compass"]

    def test_compass_json_error(self, tmp_path):
        compass_dir = tmp_path / ".claude"
        compass_dir.mkdir()
        (compass_dir / "compass.json").write_text("not json")
        pages = _collect_compass_pages(str(tmp_path))
        assert "Theory-Compass" in pages
        assert "Error loading compass" in pages["Theory-Compass"]


# ── _collect_design_pages ────────────────────────────────────────────


class TestCollectDesignPages:
    def test_docs_dir_with_md_files(self, tmp_path):
        docs = tmp_path / "docs"
        docs.mkdir()
        content = "## Architecture\n\n" + ("x" * 250)
        (docs / "design.md").write_text(content)
        pages = _collect_design_pages(str(tmp_path))
        assert "Architecture" in pages

    def test_no_docs_dir_falls_through(self, tmp_path):
        pages = _collect_design_pages(str(tmp_path))
        assert pages == {}

    def test_non_md_files_skipped(self, tmp_path):
        docs = tmp_path / "docs"
        docs.mkdir()
        (docs / "readme.txt").write_text("## Heading\n" + "x" * 300)
        pages = _collect_design_pages(str(tmp_path))
        assert pages == {}


# ── _collect_pages ───────────────────────────────────────────────────


class TestCollectPages:
    def test_single_scope(self):
        mock_collector = MagicMock(return_value={"Theory-Profile": "content"})
        with patch.dict("mcp_tools._gh_wiki_impl._SCOPE_COLLECTORS", {"theory": mock_collector}):
            pages = _collect_pages("/path", "theory")
            assert pages == {"Theory-Profile": "content"}
            mock_collector.assert_called_once_with("/path")

    def test_all_scope(self):
        collectors = {
            "theory": MagicMock(return_value={"Theory": "c1"}),
            "compass": MagicMock(return_value={"Compass": "c2"}),
            "design": MagicMock(return_value={"Arch": "c3"}),
        }
        with patch.dict("mcp_tools._gh_wiki_impl._SCOPE_COLLECTORS", collectors, clear=True):
            pages = _collect_pages("/path", "all")
            assert "Theory" in pages
            assert "Compass" in pages
            assert "Arch" in pages

    def test_unknown_scope_returns_empty(self):
        pages = _collect_pages("/path", "nonexistent")
        assert pages == {}


# ── _write_and_push_pages ────────────────────────────────────────────


class TestWriteAndPushPages:
    @patch("mcp_tools._gh_wiki_impl._push_wiki", return_value={"ok": True})
    @patch("mcp_tools._gh_wiki_impl._clone_wiki", return_value={"ok": True})
    def test_success(self, mock_clone, mock_push):
        pages = {"Test-Page": "# Test\n\nContent here."}
        result = _write_and_push_pages("/path", "owner/repo", "theory", pages)
        assert result["write"] is True
        assert result["pages_written"] == 1
        assert result["page_names"] == ["Test-Page"]
        assert result["push_result"] == {"ok": True}
        assert "next_actions" in result
        mock_clone.assert_called_once()
        mock_push.assert_called_once()

    @patch("mcp_tools._gh_wiki_impl._clone_wiki", return_value={"error": "clone failed"})
    def test_clone_error(self, mock_clone):
        result = _write_and_push_pages("/path", "owner/repo", "theory", {"p": "c"})
        assert "error" in result
        assert result["error"] == "clone failed"
        assert "hint" in result

    @patch("mcp_tools._gh_wiki_impl._push_wiki", return_value={"ok": True})
    @patch("mcp_tools._gh_wiki_impl._clone_wiki", return_value={"ok": True})
    def test_writes_files_to_tmpdir(self, mock_clone, mock_push):
        pages = {"Page-A": "aaa", "Page-B": "bbb"}
        result = _write_and_push_pages("/path", "owner/repo", "all", pages)
        assert result["pages_written"] == 2
        assert sorted(result["page_names"]) == ["Page-A", "Page-B"]


# ── impl_project_wiki_sync ──────────────────────────────────────────


class TestImplProjectWikiSync:
    def _helpers(self) -> dict[str, Any]:
        return {"_validate_project_root": MagicMock()}

    @patch("mcp_tools._gh_wiki_impl._repo_full_name", return_value="")
    def test_no_remote(self, mock_rfn):
        result = impl_project_wiki_sync("/tmp/test", "all", False, self._helpers())
        assert "error" in result
        assert "Could not detect GitHub remote" in result["error"]

    @patch("mcp_tools._gh_wiki_impl._collect_pages", return_value={"Theory": "content"})
    @patch("mcp_tools._gh_wiki_impl._repo_full_name", return_value="owner/repo")
    def test_dry_run(self, _rfn, _cp):
        result = impl_project_wiki_sync("/tmp/test", "theory", False, self._helpers())
        assert result["write"] is False
        assert result["repo"] == "owner/repo"
        assert result["scope"] == "theory"
        assert result["pages_generated"] == 1
        assert result["page_names"] == ["Theory"]
        assert result["page_sizes"] == {"Theory": 7}
        assert "next_actions" in result

    @patch("mcp_tools._gh_wiki_impl._write_and_push_pages", return_value={"write": True, "pages_written": 1})
    @patch("mcp_tools._gh_wiki_impl._collect_pages", return_value={"Theory": "content"})
    @patch("mcp_tools._gh_wiki_impl._repo_full_name", return_value="owner/repo")
    def test_write_mode(self, _rfn, _cp, mock_wpp):
        result = impl_project_wiki_sync("/tmp/test", "theory", True, self._helpers())
        assert result == {"write": True, "pages_written": 1}
        mock_wpp.assert_called_once_with("/tmp/test", "owner/repo", "theory", {"Theory": "content"})


# ── impl_project_wiki_read ──────────────────────────────────────────


class TestImplProjectWikiRead:
    def _helpers(self) -> dict[str, Any]:
        return {"_validate_project_root": MagicMock()}

    @patch("mcp_tools._gh_wiki_impl._repo_full_name", return_value="")
    def test_no_remote(self, mock_rfn):
        result = impl_project_wiki_read("/tmp/test", "Theory-Profile", self._helpers())
        assert "error" in result

    @patch("mcp_tools._gh_wiki_impl._repo_full_name", return_value="owner/repo")
    def test_local_wiki_exists(self, _rfn, tmp_path):
        wiki_dir = tmp_path / ".lintgate" / "wiki"
        wiki_dir.mkdir(parents=True)
        (wiki_dir / "Theory-Profile.md").write_text("# Local content")
        result = impl_project_wiki_read(str(tmp_path), "Theory-Profile", self._helpers())
        assert result["source"] == "local"
        assert result["content"] == "# Local content"
        assert result["page"] == "Theory-Profile"
        assert result["repo"] == "owner/repo"

    @patch("mcp_tools._gh_wiki_impl._read_remote_wiki_page", return_value={"source": "remote"})
    @patch("mcp_tools._gh_wiki_impl._repo_full_name", return_value="owner/repo")
    def test_falls_to_remote(self, _rfn, mock_remote, tmp_path):
        result = impl_project_wiki_read(str(tmp_path), "Theory-Profile", self._helpers())
        assert result["source"] == "remote"
        mock_remote.assert_called_once_with(str(tmp_path), "owner/repo", "Theory-Profile")


# ── _read_remote_wiki_page ──────────────────────────────────────────


class TestReadRemoteWikiPage:
    @patch("mcp_tools._gh_wiki_impl._clone_wiki", return_value={"error": "clone failed"})
    def test_clone_error(self, mock_clone):
        result = _read_remote_wiki_page("/path", "owner/repo", "Page")
        assert "error" in result
        assert result["error"] == "clone failed"
        assert "hint" in result

    @patch("mcp_tools._gh_wiki_impl.shutil.rmtree")
    @patch("mcp_tools._gh_wiki_impl.tempfile.mkdtemp")
    @patch("mcp_tools._gh_wiki_impl._clone_wiki", return_value={"ok": True})
    def test_page_not_found(self, mock_clone, mock_mkdtemp, mock_rmtree, tmp_path):
        mock_mkdtemp.return_value = str(tmp_path)
        # Create a different page so we get available_pages
        (tmp_path / "Home.md").write_text("home")
        (tmp_path / ".hidden.md").write_text("hidden")
        result = _read_remote_wiki_page("/path", "owner/repo", "Nonexistent")
        assert "error" in result
        assert "not found" in result["error"]
        assert "Home" in result["available_pages"]
        assert ".hidden" not in result["available_pages"]

    @patch("mcp_tools._gh_wiki_impl.shutil.rmtree")
    @patch("mcp_tools._gh_wiki_impl.tempfile.mkdtemp")
    @patch("mcp_tools._gh_wiki_impl._clone_wiki", return_value={"ok": True})
    def test_page_found(self, mock_clone, mock_mkdtemp, mock_rmtree, tmp_path):
        mock_mkdtemp.return_value = str(tmp_path)
        (tmp_path / "Theory-Profile.md").write_text("# Theory content")
        result = _read_remote_wiki_page("/path", "owner/repo", "Theory-Profile")
        assert result["source"] == "remote"
        assert result["content"] == "# Theory content"
        assert result["page"] == "Theory-Profile"
        assert "next_actions" in result
