"""Tests for work_queue."""

from __future__ import annotations

# Input examples for _compute_dependency_tiers:
#   tiers = _compute_dependency_tiers(import_graph, project_modules)
#   tiers = _compute_dependency_tiers({}, set())
#   tiers = _compute_dependency_tiers(graph, {"a", "b"})

# PROVISIONAL: characterization-backed for _compute_dependency_tiers
"""Characterization test for _compute_dependency_tiers.

Auto-generated by test_characterize. Maturity: unchecked.
Review and fill in TODO values before marking as approved.
"""


from lintgate.controlplane.work_queue import _compute_dependency_tiers


def test__compute_dependency_tiers_characterization():
    """Characterization: capture current behavior of _compute_dependency_tiers."""
    # Arrange — fill in from call-site inference
    import_graph: dict[str, list[str] | set[str]] = {}
    project_modules: set[str] = set()

    # Act
    result = _compute_dependency_tiers(import_graph, project_modules)

    # Assert
    # No golden capture — fill in expected values manually
    assert result is not None  # TODO: replace with golden assertion
