/**
 * Issue creator — create tiered GitHub issues from classified findings.
 *
 * Tier 1: Security → always create issue (label: security, auto-generated)
 * Tier 2: Mechanical → create issue with auto-fix command (label: auto-fix)
 * Tier 3: Structural → create issue with context (label: needs-reasoning)
 * Tier 4: False-positive → log only, no issue
 */

import { GITHUB_API, USER_AGENT } from "../util/constants";
import type { Finding, FindingClassification } from "../util/types";

/**
 * Create a GitHub issue for a classified finding.
 *
 * Returns the issue number if created, null if skipped.
 */
export async function createFindingIssue(
  token: string,
  owner: string,
  repo: string,
  finding: Finding,
  classification: FindingClassification,
): Promise<number | null> {
  switch (classification) {
    case "security":
      return createIssue(token, owner, repo, {
        title: `[Security] ${finding.rule}: ${truncate(finding.message, 60)}`,
        labels: ["security", "auto-generated"],
        body: formatSecurityIssue(finding),
      });

    case "mechanical":
      return createIssue(token, owner, repo, {
        title: `[Auto-fix] ${finding.rule} in ${shortPath(finding.file)}`,
        labels: ["auto-fix", "auto-generated"],
        body: formatMechanicalIssue(finding),
      });

    case "structural":
      return createIssue(token, owner, repo, {
        title: `[Quality] ${finding.rule}: ${truncate(finding.message, 60)}`,
        labels: ["needs-reasoning", "auto-generated"],
        body: formatStructuralIssue(finding),
      });

    case "false-positive":
      // Log only, no issue
      console.log(`Suppressed false-positive: ${finding.rule} in ${finding.file}`);
      return null;
  }
}

// ── Issue Formatters ────────────────────────────────────────────────

function formatSecurityIssue(finding: Finding): string {
  return [
    "## Security Finding",
    "",
    `**Rule:** \`${finding.rule}\``,
    `**Source:** ${finding.source}`,
    `**Severity:** ${finding.severity}`,
    `**File:** \`${finding.file}:${finding.line}\``,
    "",
    "### Description",
    "",
    finding.message,
    "",
    "### Action Required",
    "",
    "This finding was auto-generated by `lintgate[bot]`. Security findings require immediate attention.",
    "",
    "---",
    "*Auto-generated by lintgate[bot]*",
  ].join("\n");
}

function formatMechanicalIssue(finding: Finding): string {
  return [
    "## Mechanical Finding (Auto-fixable)",
    "",
    `**Rule:** \`${finding.rule}\``,
    `**Source:** ${finding.source}`,
    `**File:** \`${finding.file}:${finding.line}\``,
    "",
    "### Description",
    "",
    finding.message,
    "",
    "### Suggested Fix",
    "",
    "This finding can likely be auto-fixed:",
    "```bash",
    `ruff check --fix --select ${finding.rule} ${finding.file}`,
    "```",
    "",
    "---",
    "*Auto-generated by lintgate[bot]*",
  ].join("\n");
}

function formatStructuralIssue(finding: Finding): string {
  return [
    "## Structural Finding (Needs Reasoning)",
    "",
    `**Rule:** \`${finding.rule}\``,
    `**Source:** ${finding.source}`,
    `**Severity:** ${finding.severity}`,
    `**File:** \`${finding.file}:${finding.line}\``,
    "",
    "### Description",
    "",
    finding.message,
    "",
    "### Context",
    "",
    "This finding requires reasoning about code structure. Consider using",
    "`build_theory_pack` to understand project principles before making changes.",
    "",
    "---",
    "*Auto-generated by lintgate[bot]*",
  ].join("\n");
}

// ── GitHub API ──────────────────────────────────────────────────────

interface IssueParams {
  title: string;
  labels: string[];
  body: string;
}

async function createIssue(
  token: string,
  owner: string,
  repo: string,
  params: IssueParams,
): Promise<number> {
  const resp = await fetch(
    `${GITHUB_API}/repos/${owner}/${repo}/issues`,
    {
      method: "POST",
      headers: {
        Authorization: `token ${token}`,
        Accept: "application/vnd.github+json",
        "User-Agent": USER_AGENT,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(params),
    },
  );

  if (!resp.ok) {
    const text = await resp.text();
    throw new Error(`Failed to create issue: ${resp.status} ${text}`);
  }

  const data = (await resp.json()) as { number: number };
  console.log(`Created issue #${data.number}: ${params.title}`);
  return data.number;
}

// ── Helpers ─────────────────────────────────────────────────────────

function truncate(str: string, maxLen: number): string {
  if (str.length <= maxLen) return str;
  return str.slice(0, maxLen - 3) + "...";
}

function shortPath(filepath: string): string {
  const parts = filepath.split("/");
  if (parts.length <= 2) return filepath;
  return parts.slice(-2).join("/");
}
