"""Implementation for project_wiki_sync and project_wiki_read.

Extracted from gh_tools.py to keep the register() module under 400 lines.
High-CC functions are decomposed into per-scope page collectors and
separate dry-run / write-mode handlers.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import tempfile
from pathlib import Path
from typing import Any

from lintgate.next_action import NextAction, serialize_next_actions
from mcp_tools._gh_helpers import _clone_wiki, _push_wiki, _repo_full_name

# ── Page renderers ────────────────────────────────────────────────────────


def _render_theory_wiki_page(theory: dict[str, Any]) -> str:
    """Render a theory profile dict as a markdown wiki page."""
    lines = [
        "_Auto-generated by LintGate project_wiki_sync. Do not edit manually._",
        "",
        "# Theory Profile",
        "",
    ]
    facets = theory.get("facets", {})
    if not facets:
        lines.append("No theory profile extracted yet.")
        return "\n".join(lines)

    for facet_name, facet_data in facets.items():
        lines.append(f"## {facet_name.replace('_', ' ').title()}")
        lines.append("")
        claims = facet_data if isinstance(facet_data, list) else facet_data.get("claims", [])
        if not claims:
            lines.append("_No claims extracted._")
        else:
            for claim in claims[:20]:
                text = claim.get("text", claim) if isinstance(claim, dict) else str(claim)
                lines.append(f"- {text}")
        lines.append("")
    return "\n".join(lines)


def _render_compass_wiki_page(compass: dict[str, Any]) -> str:
    """Render compass state as a markdown wiki page."""
    lines = [
        "_Auto-generated by LintGate project_wiki_sync. Do not edit manually._",
        "",
        "# Project Compass",
        "",
    ]
    axes = compass.get("axes", {})
    if not axes:
        lines.append("No compass data available yet.")
        return "\n".join(lines)

    for axis_name, axis_data in axes.items():
        lines.append(f"## {axis_name.replace('_', ' ').title()}")
        lines.append("")
        if isinstance(axis_data, dict):
            _render_compass_axis(lines, axis_data)
        else:
            lines.append(f"{axis_data}")
            lines.append("")
    return "\n".join(lines)


def _render_compass_axis(lines: list[str], axis_data: dict[str, Any]) -> None:
    """Append formatted compass axis sections to *lines* (mutates in place)."""
    depth = axis_data.get("depth", "unknown")
    lines.append(f"**Depth**: {depth}")
    lines.append("")
    for section in ("toward", "away", "forbidden"):
        items = axis_data.get(section, [])
        if items:
            lines.append(f"### {section.title()}")
            for item in items:
                lines.append(f"- {item}")
            lines.append("")


def _split_design_md(design_path: str) -> dict[str, str]:
    """Split design.md by ## headings into page_name -> content dict.

    Skips sections shorter than 200 characters.
    """
    pages: dict[str, str] = {}
    try:
        with open(design_path, encoding="utf-8") as f:
            content = f.read()
    except OSError:
        return pages

    current_heading = None
    current_lines: list[str] = []

    for line in content.splitlines():
        if line.startswith("## "):
            _flush_section(pages, current_heading, current_lines)
            current_heading = line[3:].strip()
            current_lines = []
        elif current_heading is not None:
            current_lines.append(line)

    _flush_section(pages, current_heading, current_lines)
    return pages


def _flush_section(
    pages: dict[str, str],
    heading: str | None,
    lines: list[str],
) -> None:
    """Flush a design-doc section into *pages* if long enough."""
    if heading and len("\n".join(lines)) >= 200:
        slug = re.sub(r"[^a-zA-Z0-9]+", "-", heading).strip("-")
        pages[slug] = f"# {heading}\n\n" + "\n".join(lines)


# ── Per-scope page collectors ─────────────────────────────────────────────


def _collect_theory_pages(path: str) -> dict[str, str]:
    """Collect theory wiki page content."""
    try:
        from lintgate.theory_extractor import extract_theory

        theory = extract_theory(path)
        return {"Theory-Profile": _render_theory_wiki_page(theory)}
    except Exception as exc:
        return {"Theory-Profile": f"_Error extracting theory: {exc}_"}


def _collect_compass_pages(path: str) -> dict[str, str]:
    """Collect compass wiki page content."""
    try:
        compass_path = Path(path) / ".claude" / "compass.json"
        if compass_path.exists():
            with open(compass_path) as f:
                compass = json.load(f)
            return {"Theory-Compass": _render_compass_wiki_page(compass)}
        return {
            "Theory-Compass": (
                "_Auto-generated by LintGate project_wiki_sync."
                " Do not edit manually._\n\n"
                "# Project Compass\n\nNo compass data available."
                " Run `compass_update` first.\n"
            ),
        }
    except Exception as exc:
        return {"Theory-Compass": f"_Error loading compass: {exc}_"}


def _collect_design_pages(path: str) -> dict[str, str]:
    """Collect design-doc wiki pages from docs/ directory."""
    pages: dict[str, str] = {}
    docs_dir = os.path.join(path, "docs")
    if os.path.isdir(docs_dir):
        for fname in sorted(os.listdir(docs_dir)):
            if fname.endswith(".md") and os.path.isfile(os.path.join(docs_dir, fname)):
                pages.update(_split_design_md(os.path.join(docs_dir, fname)))
    else:
        design_path = os.path.join(path, "docs", "design.md")
        pages.update(_split_design_md(design_path))
    return pages


_SCOPE_COLLECTORS = {
    "theory": _collect_theory_pages,
    "compass": _collect_compass_pages,
    "design": _collect_design_pages,
}


def _collect_pages(path: str, scope: str) -> dict[str, str]:
    """Collect wiki pages for the requested scope(s)."""
    scopes = list(_SCOPE_COLLECTORS) if scope == "all" else [scope]
    pages: dict[str, str] = {}
    for s in scopes:
        collector = _SCOPE_COLLECTORS.get(s)
        if collector:
            pages.update(collector(path))
    return pages


# ── Write-mode helper ─────────────────────────────────────────────────────


def _write_and_push_pages(
    path: str,
    repo_full: str,
    scope: str,
    pages: dict[str, str],
) -> dict[str, Any]:
    """Clone wiki, write pages, push, and return result dict."""
    tmpdir = tempfile.mkdtemp(prefix="lintgate-wiki-")
    try:
        clone_result = _clone_wiki(repo_full, tmpdir)
        if clone_result.get("error"):
            return {
                "project": path,
                "repo": repo_full,
                "write": True,
                "error": clone_result["error"],
                "hint": "Ensure wiki is enabled: GitHub Settings -> Features -> Wikis. "
                "Create an initial Home page via the GitHub UI first.",
            }

        for page_name, content in pages.items():
            page_path = os.path.join(tmpdir, f"{page_name}.md")
            with open(page_path, "w", encoding="utf-8") as f:
                f.write(content)

        push_result = _push_wiki(tmpdir, f"LintGate wiki sync ({scope})")
        return {
            "project": path,
            "repo": repo_full,
            "write": True,
            "scope": scope,
            "pages_written": len(pages),
            "page_names": sorted(pages.keys()),
            "push_result": push_result,
            "next_actions": serialize_next_actions(
                [
                    NextAction(
                        tool="project_wiki_read",
                        args={"path": path, "page": "Theory-Profile"},
                        reason="Verify wiki content after sync.",
                        priority=3,
                        condition="after successful push",
                    ),
                ]
            ),
        }
    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)


# ── Top-level implementations ─────────────────────────────────────────────


def impl_project_wiki_sync(
    path: str,
    scope: str,
    write: bool,
    helpers: Any,
) -> dict[str, Any]:
    """Sync theory/compass/design data to GitHub wiki pages."""
    helpers["_validate_project_root"](path)
    repo_full = _repo_full_name(path)
    if not repo_full:
        return {"error": "Could not detect GitHub remote."}

    pages = _collect_pages(path, scope)

    if not write:
        return {
            "project": path,
            "repo": repo_full,
            "write": False,
            "scope": scope,
            "pages_generated": len(pages),
            "page_names": sorted(pages.keys()),
            "page_sizes": {k: len(v) for k, v in pages.items()},
            "next_actions": serialize_next_actions(
                [
                    NextAction(
                        tool="project_wiki_sync",
                        args={"path": path, "scope": scope, "write": True},
                        reason="Push generated pages to wiki.",
                        priority=2,
                        condition="dry-run looks good",
                    ),
                ]
            ),
        }

    return _write_and_push_pages(path, repo_full, scope, pages)


def impl_project_wiki_read(
    path: str,
    page: str,
    helpers: Any,
) -> dict[str, Any]:
    """Read a wiki page by cloning the wiki repo."""
    helpers["_validate_project_root"](path)
    repo_full = _repo_full_name(path)
    if not repo_full:
        return {"error": "Could not detect GitHub remote."}

    # Check for local wiki clone first
    local_wiki = Path(path) / ".lintgate" / "wiki"
    if local_wiki.is_dir():
        page_path = local_wiki / f"{page}.md"
        if page_path.exists():
            return {
                "project": path,
                "repo": repo_full,
                "page": page,
                "source": "local",
                "content": page_path.read_text(encoding="utf-8"),
            }

    return _read_remote_wiki_page(path, repo_full, page)


def _read_remote_wiki_page(
    path: str,
    repo_full: str,
    page: str,
) -> dict[str, Any]:
    """Clone wiki to temp dir, read a single page, return result."""
    tmpdir = tempfile.mkdtemp(prefix="lintgate-wiki-read-")
    try:
        clone_result = _clone_wiki(repo_full, tmpdir)
        if clone_result.get("error"):
            return {
                "project": path,
                "repo": repo_full,
                "page": page,
                "error": clone_result["error"],
                "hint": "Ensure wiki is enabled and has at least one page.",
            }

        page_path = os.path.join(tmpdir, f"{page}.md")
        if not os.path.exists(page_path):
            available = [
                f[:-3] for f in os.listdir(tmpdir) if f.endswith(".md") and not f.startswith(".")
            ]
            return {
                "project": path,
                "repo": repo_full,
                "page": page,
                "error": f"Page '{page}' not found",
                "available_pages": sorted(available),
            }

        with open(page_path, encoding="utf-8") as f:
            content = f.read()

        return {
            "project": path,
            "repo": repo_full,
            "page": page,
            "source": "remote",
            "content": content,
            "next_actions": serialize_next_actions(
                [
                    NextAction(
                        tool="project_wiki_sync",
                        args={"path": path, "scope": "all", "write": False},
                        reason="Sync local theory/compass to wiki.",
                        priority=4,
                        condition="wiki content needs updating",
                    ),
                ]
            ),
        }
    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)
