"""Onboarding helpers — scaffold config, quality badges, project state reset.

Extracted from onboarding_tools.py to keep the MCP registration file lean.

NOTE: ``_reset_project_state`` accesses ``Path`` through
``mcp_tools.onboarding_tools`` so that test patches targeting
``mcp_tools.onboarding_tools.Path.home`` remain effective.
"""

from __future__ import annotations

import glob as glob_mod
import hashlib
import os
import shutil
from pathlib import Path

from mcp_tools.quality_helpers import (
    _BADGE_BLOCK_END,
    _BADGE_BLOCK_START,
    _README_NAMES,
    _REQUIRED_BADGE_FINGERPRINTS,
)

_SCAFFOLD_EXCLUDED_SEGMENTS = ("/.venv/", "/__pycache__/", "/.git/", "/node_modules/")

_CONTROLPLANE_YAML_BLOCK = """\
controlplane:
  enabled: true
  severity_weighted_coherence: true
  channels:
    behavior:
      enabled: true
      thresholds:
        approach_cycling_count: 3
        failure_amnesia_lookback: 30
  inquiry:
    theory_grounded_signals: true
    prediction_tracking: true
    theory_coherence_check: true
    living_context: true
    session_gate: true
"""


# ---------------------------------------------------------------------------
# Lazy accessor — avoids circular import at load time.
# ---------------------------------------------------------------------------


def _ot():  # noqa: ANN202
    """Return the onboarding_tools module."""
    import mcp_tools.onboarding_tools as _mod

    return _mod


def _collect_python_files(project_root: str) -> list[str]:
    """Return sorted, filtered list of Python source files under *project_root*."""
    py_files = sorted(glob_mod.glob(os.path.join(project_root, "**", "*.py"), recursive=True))
    return [f for f in py_files if not any(seg in f for seg in _SCAFFOLD_EXCLUDED_SEGMENTS)]


def _find_critical_paths(py_files: list[str], project_root: str) -> list[str]:
    """Identify Python files exceeding 300 lines (potential critical paths)."""
    critical: list[str] = []
    for fpath in py_files:
        try:
            with open(fpath) as f:
                line_count = sum(1 for _ in f)
        except OSError:
            continue
        if line_count > 300:
            critical.append(os.path.relpath(fpath, project_root))
    return sorted(critical)[:10]


def _has_subprocess_usage(py_files: list[str]) -> bool:
    """Check whether any of the first 50 source files import subprocess."""
    for fpath in py_files[:50]:
        try:
            with open(fpath) as f:
                content = f.read(8192)
        except OSError:
            continue
        if "subprocess" in content:
            return True
    return False


def _scaffold_config_yaml(project_root: str, helpers: dict) -> str:
    """Analyze project and generate a tailored lintgate.yaml."""
    lines: list[str] = [
        "# LintGate configuration — generated by scaffold_config",
        "# Review and adjust to match your project's needs.",
        "",
    ]

    py_files = _collect_python_files(project_root)

    critical_paths = _find_critical_paths(py_files, project_root)
    if critical_paths:
        lines.append("pipeline_critical_paths:")
        for cp in critical_paths:
            lines.append(f'  - "{cp}"')
        lines.append("")

    if _has_subprocess_usage(py_files):
        lines.append("severity_overrides:")
        lines.append("  B603: informational  # subprocess calls — expected for tool orchestration")
        lines.append("  B107: informational  # hardcoded passwords — review if unexpected")
        lines.append("")

    lines.append(_CONTROLPLANE_YAML_BLOCK)

    return "\n".join(lines) + "\n"


def _readme_has_quality_badges(project_root: str) -> bool:
    """Return True if README contains the minimum badge fingerprints."""
    root = Path(project_root)
    readme_path: Path | None = None
    for name in _README_NAMES:
        candidate = root / name
        if candidate.exists():
            readme_path = candidate
            break

    if readme_path is None:
        return False

    try:
        content = readme_path.read_text(errors="ignore")
    except OSError:
        return False

    if _BADGE_BLOCK_START in content and _BADGE_BLOCK_END in content:
        start = content.find(_BADGE_BLOCK_START)
        end = content.find(_BADGE_BLOCK_END, start)
        if end == -1:
            return False
        managed_block = content[start : end + len(_BADGE_BLOCK_END)]
        return all(fp in managed_block for fp in _REQUIRED_BADGE_FINGERPRINTS)

    return all(fp in content for fp in _REQUIRED_BADGE_FINGERPRINTS)


def _reset_project_state(project_root: str) -> list[dict[str, str]]:
    """Reset project state directories while preserving config.

    Clears:
    - .claude/lintgate/state/     (session state, compass, habit)
    - .claude/lintgate/runs/      (lint run history)
    - .claude/lintgate/sessions/  (session memory)

    Does NOT touch:
    - .claude/lintgate.yaml       (config preserved)
    - .claude/lintgate/issue_memory.json (accumulated issue data)

    Returns list of {"action": ..., "path": ...} for audit.
    """
    ot = _ot()
    actions: list[dict[str, str]] = []
    lintgate_dir = os.path.join(project_root, ".claude", "lintgate")

    state_dirs = ["state", "runs", "sessions"]
    for subdir in state_dirs:
        target = os.path.join(lintgate_dir, subdir)
        if os.path.isdir(target):
            shutil.rmtree(target)
            actions.append({"action": "reset_dir", "path": target})

    # Also clear project-hash-keyed habit state files under LINTGATE_HOME
    lintgate_home = os.environ.get("LINTGATE_HOME")
    habit_base = (
        ot.Path(lintgate_home) / "habit_state"
        if lintgate_home
        else ot.Path.home() / ".lintgate" / "habit_state"
    )
    if habit_base.is_dir():
        # Compute project hash to find matching habit state files
        project_hash = hashlib.sha256(os.path.abspath(project_root).encode()).hexdigest()[:12]
        for item in habit_base.iterdir():
            if item.is_file() and project_hash in item.name:
                item.unlink()
                actions.append({"action": "reset_file", "path": str(item)})

    return actions
