"""GitHub project organization and wiki sync tools."""

from __future__ import annotations

import contextlib
import json
import os
import re
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Any

from lintgate.next_action import NextAction, serialize_next_actions

# GitHub remote detection pattern (reused from quality_helpers.py)
_GITHUB_REMOTE_RE = re.compile(
    r"(?:github\.com)[:/]([^/]+)/([^/\s]+?)(?:\.git)?(?:\s|$)",
)


# ─── Internal helpers ─────────────────────────────────────────────────────


def _run_gh(args: list[str], cwd: str | None = None) -> dict[str, Any]:
    """Run a ``gh`` CLI command and return parsed JSON or error dict."""
    try:
        proc = subprocess.run(
            ["gh", *args],
            capture_output=True,
            text=True,
            cwd=cwd,
            timeout=30,
        )
        if proc.returncode != 0:
            return {"error": proc.stderr.strip() or f"gh exited with {proc.returncode}"}
        if not proc.stdout.strip():
            return {}
        try:
            return json.loads(proc.stdout)
        except json.JSONDecodeError:
            return {"raw": proc.stdout.strip()}
    except FileNotFoundError:
        return {"error": "gh CLI not found. Install: https://cli.github.com/"}
    except subprocess.TimeoutExpired:
        return {"error": "gh command timed out after 30s"}


def _detect_repo(project_root: str) -> dict[str, str]:
    """Detect GitHub owner/repo from git remote."""
    try:
        proc = subprocess.run(
            ["git", "-C", project_root, "remote", "-v"],
            capture_output=True,
            text=True,
            check=True,
        )
        for line in proc.stdout.splitlines():
            match = _GITHUB_REMOTE_RE.search(line)
            if match:
                return {"owner": match.group(1), "repo": match.group(2)}
    except (subprocess.CalledProcessError, FileNotFoundError):
        pass
    return {"owner": "", "repo": ""}


def _repo_full_name(project_root: str) -> str:
    """Return 'owner/repo' string or empty string."""
    info = _detect_repo(project_root)
    if info["owner"] and info["repo"]:
        return f"{info['owner']}/{info['repo']}"
    return ""


def _clone_wiki(repo_full: str, target_dir: str) -> dict[str, Any]:
    """Clone wiki repo (shallow) into target_dir."""
    url = f"https://github.com/{repo_full}.wiki.git"
    try:
        subprocess.run(
            ["git", "clone", "--depth=1", url, target_dir],
            capture_output=True,
            text=True,
            check=True,
            timeout=30,
        )
        return {"ok": True}
    except subprocess.CalledProcessError as exc:
        return {"error": f"Wiki clone failed: {exc.stderr.strip()}"}
    except subprocess.TimeoutExpired:
        return {"error": "Wiki clone timed out after 30s"}


def _push_wiki(wiki_dir: str, message: str) -> dict[str, Any]:
    """Stage all changes, commit, and push in a wiki clone."""
    try:
        subprocess.run(
            ["git", "add", "-A"],
            cwd=wiki_dir, capture_output=True, text=True, check=True,
        )
        # Check if there's anything to commit
        status = subprocess.run(
            ["git", "status", "--porcelain"],
            cwd=wiki_dir, capture_output=True, text=True, check=True,
        )
        if not status.stdout.strip():
            return {"ok": True, "message": "No changes to push"}
        subprocess.run(
            ["git", "commit", "-m", message],
            cwd=wiki_dir, capture_output=True, text=True, check=True,
        )
        subprocess.run(
            ["git", "push"],
            cwd=wiki_dir, capture_output=True, text=True, check=True,
            timeout=30,
        )
        return {"ok": True}
    except subprocess.CalledProcessError as exc:
        return {"error": f"Wiki push failed: {exc.stderr.strip()}"}
    except subprocess.TimeoutExpired:
        return {"error": "Wiki push timed out after 30s"}


def _render_theory_wiki_page(theory: dict[str, Any]) -> str:
    """Render a theory profile dict as a markdown wiki page."""
    lines = [
        "_Auto-generated by LintGate project_wiki_sync. Do not edit manually._",
        "",
        "# Theory Profile",
        "",
    ]
    facets = theory.get("facets", {})
    if not facets:
        lines.append("No theory profile extracted yet.")
        return "\n".join(lines)

    for facet_name, facet_data in facets.items():
        lines.append(f"## {facet_name.replace('_', ' ').title()}")
        lines.append("")
        claims = facet_data if isinstance(facet_data, list) else facet_data.get("claims", [])
        if not claims:
            lines.append("_No claims extracted._")
        else:
            for claim in claims[:20]:
                text = claim.get("text", claim) if isinstance(claim, dict) else str(claim)
                lines.append(f"- {text}")
        lines.append("")
    return "\n".join(lines)


def _render_compass_wiki_page(compass: dict[str, Any]) -> str:
    """Render compass state as a markdown wiki page."""
    lines = [
        "_Auto-generated by LintGate project_wiki_sync. Do not edit manually._",
        "",
        "# Project Compass",
        "",
    ]
    axes = compass.get("axes", {})
    if not axes:
        lines.append("No compass data available yet.")
        return "\n".join(lines)

    for axis_name, axis_data in axes.items():
        lines.append(f"## {axis_name.replace('_', ' ').title()}")
        lines.append("")
        if isinstance(axis_data, dict):
            depth = axis_data.get("depth", "unknown")
            lines.append(f"**Depth**: {depth}")
            lines.append("")
            toward = axis_data.get("toward", [])
            if toward:
                lines.append("### Toward")
                for item in toward:
                    lines.append(f"- {item}")
                lines.append("")
            away = axis_data.get("away", [])
            if away:
                lines.append("### Away")
                for item in away:
                    lines.append(f"- {item}")
                lines.append("")
            forbidden = axis_data.get("forbidden", [])
            if forbidden:
                lines.append("### Forbidden")
                for item in forbidden:
                    lines.append(f"- {item}")
                lines.append("")
        else:
            lines.append(f"{axis_data}")
            lines.append("")
    return "\n".join(lines)


def _split_design_md(design_path: str) -> dict[str, str]:
    """Split design.md by ## headings into page_name → content dict.

    Skips sections shorter than 200 characters.
    """
    pages: dict[str, str] = {}
    try:
        with open(design_path, encoding="utf-8") as f:
            content = f.read()
    except OSError:
        return pages

    current_heading = None
    current_lines: list[str] = []

    for line in content.splitlines():
        if line.startswith("## "):
            # Flush previous section
            if current_heading and len("\n".join(current_lines)) >= 200:
                slug = re.sub(r"[^a-zA-Z0-9]+", "-", current_heading).strip("-")
                pages[slug] = f"# {current_heading}\n\n" + "\n".join(current_lines)
            current_heading = line[3:].strip()
            current_lines = []
        elif current_heading is not None:
            current_lines.append(line)

    # Flush last section
    if current_heading and len("\n".join(current_lines)) >= 200:
        slug = re.sub(r"[^a-zA-Z0-9]+", "-", current_heading).strip("-")
        pages[slug] = f"# {current_heading}\n\n" + "\n".join(current_lines)

    return pages


# ─── Tool implementations ─────────────────────────────────────────────────


def _impl_project_organize_audit(
    path: str,
    helpers: Any,
) -> dict[str, Any]:
    """Scan GitHub project state and report organizational gaps."""
    helpers["_validate_project_root"](path)
    repo_full = _repo_full_name(path)
    gaps: list[dict[str, Any]] = []

    # ORG001: Check for issue templates
    template_dir = Path(path) / ".github" / "ISSUE_TEMPLATE"
    if not template_dir.is_dir():
        gaps.append({
            "code": "ORG001",
            "message": "No .github/ISSUE_TEMPLATE/ directory",
            "severity": "medium",
        })

    if not repo_full:
        return {
            "project": path,
            "repo": None,
            "gaps": gaps,
            "error": "Could not detect GitHub remote. Skipping API-based checks.",
            "next_actions": serialize_next_actions([
                NextAction(
                    tool="project_organize_apply",
                    args={"path": path, "write": False},
                    reason="Preview organization changes.",
                    priority=3,
                ),
            ]),
        }

    # ORG002: Check for priority labels
    labels_result = _run_gh(
        ["label", "list", "--repo", repo_full, "--json", "name", "--limit", "200"],
    )
    label_names: list[str] = []
    if isinstance(labels_result, list):
        label_names = [lb.get("name", "") for lb in labels_result]
    elif isinstance(labels_result, dict) and not labels_result.get("error"):
        raw = labels_result.get("raw", "")
        if raw:
            try:
                parsed = json.loads(raw)
                if isinstance(parsed, list):
                    label_names = [lb.get("name", "") for lb in parsed]
            except json.JSONDecodeError:
                pass

    priority_labels = [n for n in label_names if re.match(r"^P[0-3]$", n)]
    if len(priority_labels) < 4:
        missing = [f"P{i}" for i in range(4) if f"P{i}" not in label_names]
        gaps.append({
            "code": "ORG002",
            "message": f"Missing priority labels: {', '.join(missing)}",
            "severity": "low",
        })

    # ORG003: Check for type: prefix labels
    type_labels = [n for n in label_names if n.startswith("type:")]
    if not type_labels:
        gaps.append({
            "code": "ORG003",
            "message": "No type: prefix labels defined",
            "severity": "low",
        })

    # ORG004: Issues with no labels
    issues_result = _run_gh(
        ["issue", "list", "--repo", repo_full, "--json", "number,labels",
         "--state", "open", "--limit", "500"],
    )
    issues_list: list[dict] = []
    if isinstance(issues_result, list):
        issues_list = issues_result
    elif isinstance(issues_result, dict):
        raw = issues_result.get("raw", "")
        if raw:
            try:
                parsed = json.loads(raw)
                if isinstance(parsed, list):
                    issues_list = parsed
            except json.JSONDecodeError:
                pass

    unlabeled = [
        iss["number"] for iss in issues_list
        if not iss.get("labels")
    ]
    if unlabeled:
        gaps.append({
            "code": "ORG004",
            "message": f"{len(unlabeled)} issues have no labels",
            "severity": "medium",
            "issues": unlabeled[:20],
        })

    # ORG005: No milestones
    if len(issues_list) > 10:
        milestones_result = _run_gh(
            ["api", f"repos/{repo_full}/milestones", "--jq", "length"],
        )
        ms_count = 0
        if isinstance(milestones_result, dict):
            raw = milestones_result.get("raw", "0")
            with contextlib.suppress(ValueError, TypeError):
                ms_count = int(raw)
        if ms_count == 0:
            gaps.append({
                "code": "ORG005",
                "message": f"No milestones defined (repo has {len(issues_list)}+ open issues)",
                "severity": "low",
            })

    # ORG006: Wiki disabled
    repo_info = _run_gh(
        ["api", f"repos/{repo_full}", "--jq", ".has_wiki"],
    )
    if isinstance(repo_info, dict):
        raw = repo_info.get("raw", "")
        if raw.strip().lower() == "false":
            gaps.append({
                "code": "ORG006",
                "message": "Wiki is disabled on this repository",
                "severity": "low",
            })

    # ORG007: Issues missing priority labels
    if priority_labels and issues_list:
        no_priority = [
            iss["number"] for iss in issues_list
            if not any(
                lb.get("name", "").startswith("P") and len(lb.get("name", "")) == 2
                for lb in (iss.get("labels") or [])
            )
        ]
        if no_priority:
            gaps.append({
                "code": "ORG007",
                "message": f"{len(no_priority)} issues missing priority labels",
                "severity": "low",
                "issues": no_priority[:20],
            })

    return {
        "project": path,
        "repo": repo_full,
        "total_gaps": len(gaps),
        "gaps": gaps,
        "labels_found": len(label_names),
        "open_issues": len(issues_list),
        "next_actions": serialize_next_actions([
            NextAction(
                tool="project_organize_apply",
                args={"path": path, "write": False},
                reason="Preview fixes for detected gaps.",
                priority=2,
                condition="gaps detected",
            ),
            NextAction(
                tool="project_wiki_sync",
                args={"path": path, "scope": "all", "write": False},
                reason="Preview wiki page generation.",
                priority=4,
                condition="wiki infrastructure desired",
            ),
        ]),
    }


def _impl_project_organize_apply(
    path: str,
    actions: list[str] | None,
    write: bool,
    helpers: Any,
) -> dict[str, Any]:
    """Apply organization changes. Dry-run by default."""
    helpers["_validate_project_root"](path)
    repo_full = _repo_full_name(path)
    if not repo_full:
        return {"error": "Could not detect GitHub remote."}

    planned: list[dict[str, Any]] = []
    applied: list[dict[str, Any]] = []

    # Determine what to apply
    all_actions = actions or ["labels", "milestones"]

    if "labels" in all_actions:
        # Check existing labels
        labels_result = _run_gh(
            ["label", "list", "--repo", repo_full, "--json", "name", "--limit", "200"],
        )
        existing: list[str] = []
        if isinstance(labels_result, list):
            existing = [lb.get("name", "") for lb in labels_result]
        elif isinstance(labels_result, dict) and not labels_result.get("error"):
            raw = labels_result.get("raw", "")
            if raw:
                try:
                    parsed = json.loads(raw)
                    if isinstance(parsed, list):
                        existing = [lb.get("name", "") for lb in parsed]
                except json.JSONDecodeError:
                    pass

        # Priority labels
        priority_colors = {"P0": "B60205", "P1": "D93F0B", "P2": "FBCA04", "P3": "0E8A16"}
        for label, color in priority_colors.items():
            if label not in existing:
                action = {"type": "create_label", "name": label, "color": color}
                planned.append(action)
                if write:
                    result = _run_gh([
                        "label", "create", label,
                        "--repo", repo_full,
                        "--color", color,
                        "--description", f"Priority {label}",
                    ])
                    action["result"] = result
                    applied.append(action)

        # Type labels
        type_labels = {
            "type:research": "1D76DB",
            "type:architecture": "5319E7",
            "type:bug": "B60205",
            "type:refactor": "FBCA04",
        }
        for label, color in type_labels.items():
            if label not in existing:
                action = {"type": "create_label", "name": label, "color": color}
                planned.append(action)
                if write:
                    result = _run_gh([
                        "label", "create", label,
                        "--repo", repo_full,
                        "--color", color,
                    ])
                    action["result"] = result
                    applied.append(action)

    return {
        "project": path,
        "repo": repo_full,
        "write": write,
        "planned_actions": len(planned),
        "applied_actions": len(applied),
        "actions": planned if not write else applied,
        "next_actions": serialize_next_actions([
            NextAction(
                tool="project_organize_apply",
                args={"path": path, "actions": all_actions, "write": True},
                reason="Apply planned changes.",
                priority=2,
                condition="dry-run looks good and write=False was used",
            ),
            NextAction(
                tool="project_organize_audit",
                args={"path": path},
                reason="Re-audit after applying changes.",
                priority=3,
                condition="after applying changes",
            ),
        ]),
    }


def _impl_project_wiki_sync(
    path: str,
    scope: str,
    write: bool,
    helpers: Any,
) -> dict[str, Any]:
    """Sync theory/compass/design data to GitHub wiki pages."""
    helpers["_validate_project_root"](path)
    repo_full = _repo_full_name(path)
    if not repo_full:
        return {"error": "Could not detect GitHub remote."}

    pages: dict[str, str] = {}
    scopes = [scope] if scope != "all" else ["theory", "compass", "design"]

    if "theory" in scopes:
        try:
            from lintgate.theory_extractor import extract_theory
            theory = extract_theory(path)
            pages["Theory-Profile"] = _render_theory_wiki_page(theory)
        except Exception as exc:
            pages["Theory-Profile"] = f"_Error extracting theory: {exc}_"

    if "compass" in scopes:
        try:
            compass_path = Path(path) / ".claude" / "compass.json"
            if compass_path.exists():
                with open(compass_path) as f:
                    compass = json.load(f)
                pages["Theory-Compass"] = _render_compass_wiki_page(compass)
            else:
                pages["Theory-Compass"] = (
                    "_Auto-generated by LintGate project_wiki_sync."
                    " Do not edit manually._\n\n"
                    "# Project Compass\n\nNo compass data available."
                    " Run `compass_update` first.\n"
                )
        except Exception as exc:
            pages["Theory-Compass"] = f"_Error loading compass: {exc}_"

    if "design" in scopes:
        docs_dir = os.path.join(path, "docs")
        if os.path.isdir(docs_dir):
            for fname in sorted(os.listdir(docs_dir)):
                if fname.endswith(".md") and os.path.isfile(os.path.join(docs_dir, fname)):
                    design_pages = _split_design_md(os.path.join(docs_dir, fname))
                    pages.update(design_pages)
        else:
            # Fallback: single design.md
            design_path = os.path.join(path, "docs", "design.md")
            design_pages = _split_design_md(design_path)
            pages.update(design_pages)

    if not write:
        return {
            "project": path,
            "repo": repo_full,
            "write": False,
            "scope": scope,
            "pages_generated": len(pages),
            "page_names": sorted(pages.keys()),
            "page_sizes": {k: len(v) for k, v in pages.items()},
            "next_actions": serialize_next_actions([
                NextAction(
                    tool="project_wiki_sync",
                    args={"path": path, "scope": scope, "write": True},
                    reason="Push generated pages to wiki.",
                    priority=2,
                    condition="dry-run looks good",
                ),
            ]),
        }

    # Write mode: clone wiki, write pages, push
    tmpdir = tempfile.mkdtemp(prefix="lintgate-wiki-")
    try:
        clone_result = _clone_wiki(repo_full, tmpdir)
        if clone_result.get("error"):
            return {
                "project": path,
                "repo": repo_full,
                "write": True,
                "error": clone_result["error"],
                "hint": "Ensure wiki is enabled: GitHub Settings → Features → Wikis. "
                        "Create an initial Home page via the GitHub UI first.",
            }

        for page_name, content in pages.items():
            page_path = os.path.join(tmpdir, f"{page_name}.md")
            with open(page_path, "w", encoding="utf-8") as f:
                f.write(content)

        push_result = _push_wiki(tmpdir, f"LintGate wiki sync ({scope})")
        return {
            "project": path,
            "repo": repo_full,
            "write": True,
            "scope": scope,
            "pages_written": len(pages),
            "page_names": sorted(pages.keys()),
            "push_result": push_result,
            "next_actions": serialize_next_actions([
                NextAction(
                    tool="project_wiki_read",
                    args={"path": path, "page": "Theory-Profile"},
                    reason="Verify wiki content after sync.",
                    priority=3,
                    condition="after successful push",
                ),
            ]),
        }
    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)


def _impl_project_wiki_read(
    path: str,
    page: str,
    helpers: Any,
) -> dict[str, Any]:
    """Read a wiki page by cloning the wiki repo."""
    helpers["_validate_project_root"](path)
    repo_full = _repo_full_name(path)
    if not repo_full:
        return {"error": "Could not detect GitHub remote."}

    # Check for local wiki clone first
    local_wiki = Path(path) / ".lintgate" / "wiki"
    if local_wiki.is_dir():
        page_path = local_wiki / f"{page}.md"
        if page_path.exists():
            return {
                "project": path,
                "repo": repo_full,
                "page": page,
                "source": "local",
                "content": page_path.read_text(encoding="utf-8"),
            }

    # Clone to temp dir
    tmpdir = tempfile.mkdtemp(prefix="lintgate-wiki-read-")
    try:
        clone_result = _clone_wiki(repo_full, tmpdir)
        if clone_result.get("error"):
            return {
                "project": path,
                "repo": repo_full,
                "page": page,
                "error": clone_result["error"],
                "hint": "Ensure wiki is enabled and has at least one page.",
            }

        page_path = os.path.join(tmpdir, f"{page}.md")
        if not os.path.exists(page_path):
            available = [
                f[:-3] for f in os.listdir(tmpdir)
                if f.endswith(".md") and not f.startswith(".")
            ]
            return {
                "project": path,
                "repo": repo_full,
                "page": page,
                "error": f"Page '{page}' not found",
                "available_pages": sorted(available),
            }

        with open(page_path, encoding="utf-8") as f:
            content = f.read()

        return {
            "project": path,
            "repo": repo_full,
            "page": page,
            "source": "remote",
            "content": content,
            "next_actions": serialize_next_actions([
                NextAction(
                    tool="project_wiki_sync",
                    args={"path": path, "scope": "all", "write": False},
                    reason="Sync local theory/compass to wiki.",
                    priority=4,
                    condition="wiki content needs updating",
                ),
            ]),
        }
    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)


# ─── Registration ─────────────────────────────────────────────────────────


def register(mcp: Any, helpers: Any) -> dict[str, Any]:
    """Register GitHub organization tools on the shared MCP instance."""

    @mcp.tool()
    def project_organize_audit(
        path: str,
    ) -> str:
        """Audit GitHub project organization and report gaps.

        WHEN TO USE: When starting a project or reviewing its GitHub setup.
        Checks for issue templates, labels, milestones, and wiki status.

        Returns structured gap report with codes ORG001-ORG007.

        Example: project_organize_audit(path="/my/project")

        Args:
            path: Project root path.
        """
        return json.dumps(_impl_project_organize_audit(path, helpers))

    @mcp.tool()
    def project_organize_apply(
        path: str,
        actions: list[str] | None = None,
        write: bool = False,
    ) -> str:
        """Apply organization changes (labels, milestones). Dry-run by default.

        WHEN TO USE: After project_organize_audit identifies gaps. Use with
        write=False first to preview changes, then write=True to apply.

        Actions: 'labels' (create missing P0-P3 and type: labels),
        'milestones' (create milestone from issue cluster analysis).

        Example: project_organize_apply(path="/my/project")
        Example: project_organize_apply(path="/my/project", write=True)

        Args:
            path: Project root path.
            actions: List of action types to apply. Default: ['labels', 'milestones'].
            write: If False (default), dry-run showing what would happen.
        """
        return json.dumps(_impl_project_organize_apply(path, actions, write, helpers))

    @mcp.tool()
    def project_wiki_sync(
        path: str,
        scope: str = "theory",
        write: bool = False,
    ) -> str:
        """Sync theory/compass/design data to GitHub wiki pages. Dry-run by default.

        WHEN TO USE: To publish project theory, compass, or design docs to the
        GitHub wiki. Use scope='all' for full sync.

        Scopes: 'theory' (theory profile), 'compass' (compass axes),
        'design' (split docs/design.md by headings), 'all' (all scopes).

        Requires wiki to be enabled on the repo with at least one initial page.

        Example: project_wiki_sync(path="/my/project", scope="all")
        Example: project_wiki_sync(path="/my/project", scope="theory", write=True)

        Args:
            path: Project root path.
            scope: What to sync: 'theory', 'compass', 'design', or 'all'.
            write: If False (default), show what pages would be generated.
        """
        return json.dumps(_impl_project_wiki_sync(path, scope, write, helpers))

    @mcp.tool()
    def project_wiki_read(
        path: str,
        page: str = "Home",
    ) -> str:
        """Read a GitHub wiki page. Checks local clone first, then remote.

        WHEN TO USE: To read wiki content for theory extraction integration.
        Wiki content can feed back into theory claims via the .lintgate/wiki/
        local clone.

        Example: project_wiki_read(path="/my/project")
        Example: project_wiki_read(path="/my/project", page="Theory-Profile")

        Args:
            path: Project root path.
            page: Wiki page name (without .md extension). Default: 'Home'.
        """
        return json.dumps(_impl_project_wiki_read(path, page, helpers))

    return {
        "project_organize_audit": project_organize_audit,
        "project_organize_apply": project_organize_apply,
        "project_wiki_sync": project_wiki_sync,
        "project_wiki_read": project_wiki_read,
    }
