"""C3: Behavioral contract generator — deterministic, symbolic only.

Generates test assertions from AST patterns. Three strategies:

1. Return type assertions — from type annotations or AST inference
2. Shape preservation — from loop structure (map/filter patterns)
3. Error boundary assertions — from exception handlers

Plus I/O stub detection for subprocess/HTTP/file calls.

No LLM calls. Fully deterministic.
"""

from __future__ import annotations

import ast
import os
from typing import Any

# I/O call patterns that indicate impure functions needing mock stubs
_IO_MODULES = frozenset(
    {
        "subprocess",
        "os",
        "shutil",
        "tempfile",
        "requests",
        "urllib",
        "http",
        "httpx",
        "aiohttp",
        "open",  # builtin
        "pathlib",
        "socket",
        "smtplib",
        "json",  # only when combined with file I/O
    }
)

_IO_FUNCTION_NAMES = frozenset(
    {
        "open",
        "read",
        "write",
        "run",
        "call",
        "check_output",
        "check_call",
        "Popen",
        "get",
        "post",
        "put",
        "delete",
        "patch",
        "request",
        "urlopen",
        "urlretrieve",
        "makedirs",
        "mkdir",
        "rmdir",
        "remove",
        "unlink",
        "rename",
        "copy",
        "copy2",
        "copytree",
        "move",
        "send",
        "recv",
        "connect",
    }
)


def generate_contracts(
    project_root: str,
    manifest: Any | None = None,
) -> dict[str, str]:
    """Generate behavioral contracts for source files in a project.

    Args:
        project_root: Project root path.
        manifest: Optional PropertyManifest from algebra survey.

    Returns:
        Dict of test_path → contract test content.
    """
    from pathlib import Path

    results: dict[str, str] = {}
    root = Path(project_root)
    gen_dir = os.path.join(project_root, "tests", "generated")

    for py_file in sorted(root.rglob("*.py")):
        # Skip tests, configs, hidden dirs
        resolved = str(py_file.resolve())
        if any(seg in resolved for seg in ("/site-packages/", "/dist-packages/")):
            continue
        name = py_file.stem
        if name.startswith("test_") or name.endswith("_test"):
            continue
        if name in ("__init__", "setup", "conftest"):
            continue
        if any(part.startswith(".") for part in py_file.parts):
            continue
        if any(
            part in ("node_modules", "venv", ".venv", "build", "dist")
            for part in py_file.parts
        ):
            continue

        try:
            source = py_file.read_text(encoding="utf-8", errors="ignore")
            tree = ast.parse(source, filename=str(py_file))
        except (SyntaxError, UnicodeDecodeError):
            continue

        contracts = _generate_file_contracts(tree, str(py_file), project_root)
        if contracts:
            safe_name = name.replace(".", "_")
            test_path = os.path.join(gen_dir, f"test_contracts_{safe_name}.py")
            header = (
                "# Auto-generated by LintGate bootstrap — review before relying on\n"
            )
            module_path = _compute_import_path(str(py_file), project_root)
            imports = f'"""Behavioral contracts for {name}."""\n\nfrom __future__ import annotations\n\n'
            if module_path:
                imports += f"# Source module: {module_path}\n"
            imports += "\n"
            results[test_path] = header + imports + "\n".join(contracts) + "\n"

    return results


def _generate_file_contracts(
    tree: ast.Module,
    filepath: str,
    project_root: str,
) -> list[str]:
    """Generate contracts for all functions in a file."""
    contracts: list[str] = []
    module_path = _compute_import_path(filepath, project_root)

    for node in ast.walk(tree):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        # Skip private/dunder
        if node.name.startswith("_"):
            continue

        func_contracts = _generate_function_contracts(node, module_path)
        if func_contracts:
            contracts.extend(func_contracts)

    return contracts


def _generate_function_contracts(
    func: ast.FunctionDef | ast.AsyncFunctionDef,
    module_path: str,
) -> list[str]:
    """Generate contracts for a single function."""
    parts: list[str] = []

    # Strategy 1: Return type assertions
    rt_contract = _generate_return_type_contract(func, module_path)
    if rt_contract:
        parts.append(rt_contract)

    # Strategy 2: Shape preservation (map/filter patterns)
    shape_contract = _generate_shape_contract(func, module_path)
    if shape_contract:
        parts.append(shape_contract)

    # Strategy 3: Error boundary assertions
    error_contract = _generate_error_boundary_contract(func, module_path)
    if error_contract:
        parts.append(error_contract)

    # Strategy 4: I/O stubs (TODO markers)
    io_stub = _generate_io_stub(func, module_path)
    if io_stub:
        parts.append(io_stub)

    return parts


# ── Strategy 1: Return Type Contracts ────────────────────────────────────


def _generate_return_type_contract(
    func: ast.FunctionDef | ast.AsyncFunctionDef,
    module_path: str,
) -> str | None:
    """Generate return type assertion from type annotations."""
    if func.returns is None:
        return None

    type_str = _annotation_to_str(func.returns)
    if not type_str or type_str == "None":
        return None

    # Map annotation to isinstance check
    isinstance_type = _annotation_to_isinstance(type_str)
    if not isinstance_type:
        return None

    fn = func.name
    args_placeholder = _make_args_placeholder(func)
    import_line = f"from {module_path} import {fn}" if module_path else ""

    lines = [
        f"def test_{fn}_returns_{type_str.lower().replace('[', '_').replace(']', '').replace(', ', '_')}() -> None:",
        f'    """Contract: {fn} returns {type_str}."""',
    ]
    if import_line:
        lines.insert(0, f"# {import_line}")
    lines.extend(
        [
            "    # TODO: Provide valid arguments",
            f"    # result = {fn}({args_placeholder})",
            f"    # assert isinstance(result, {isinstance_type})",
            "",
        ]
    )
    return "\n".join(lines)


# ── Strategy 2: Shape Preservation ───────────────────────────────────────


def _generate_shape_contract(
    func: ast.FunctionDef | ast.AsyncFunctionDef,
    module_path: str,
) -> str | None:
    """Detect map/filter patterns and generate shape contracts.

    Pattern: for item in input: result.append(transform(item))
    Contract: assert len(result) == len(input)
    """
    # Look for: result = []; for x in param: result.append(...)
    body = func.body
    has_init_list = False
    has_for_append = False
    input_param: str | None = None

    for stmt in body:
        # Check for list initialization: result = []
        if isinstance(stmt, ast.Assign) and len(stmt.targets) == 1:
            if isinstance(stmt.value, ast.List) and len(stmt.value.elts) == 0:
                has_init_list = True

        # Check for: for x in param: ... result.append(...)
        if isinstance(stmt, ast.For) and has_init_list:
            iter_node = stmt.iter
            if isinstance(iter_node, ast.Name):
                input_param = iter_node.id
            # Check body for .append() call
            for sub_stmt in ast.walk(stmt):
                if isinstance(sub_stmt, ast.Call):
                    if isinstance(sub_stmt.func, ast.Attribute) and sub_stmt.func.attr == "append":
                        has_for_append = True

    if not (has_init_list and has_for_append and input_param):
        return None

    fn = func.name
    lines = [
        f"def test_{fn}_preserves_length() -> None:",
        f'    """Contract: {fn} output length matches input length (map pattern)."""',
        f"    # TODO: Provide test input for '{input_param}'",
        "    # input_data = [...]",
        f"    # result = {fn}(input_data)",
        "    # assert len(result) == len(input_data)",
        "",
    ]
    return "\n".join(lines)


# ── Strategy 3: Error Boundary ───────────────────────────────────────────


def _generate_error_boundary_contract(
    func: ast.FunctionDef | ast.AsyncFunctionDef,
    module_path: str,
) -> str | None:
    """Detect except handlers that return defaults and generate contracts.

    Pattern: except: return [] → assert func(bad_input) == []
    """
    for stmt in ast.walk(func):
        if not isinstance(stmt, ast.ExceptHandler):
            continue

        # Look for return statements in the handler
        for sub in ast.walk(stmt):
            if not isinstance(sub, ast.Return) or sub.value is None:
                continue

            default_str = _value_to_str(sub.value)
            if default_str is None:
                continue

            fn = func.name
            exc_type = "Exception"
            if stmt.type is not None:
                exc_type = _annotation_to_str(stmt.type) or "Exception"

            lines = [
                f"def test_{fn}_returns_default_on_{exc_type.lower()}() -> None:",
                f'    """Contract: {fn} returns {default_str} on {exc_type}."""',
                f"    # When {exc_type} occurs, function should return {default_str}",
                "    # TODO: Trigger the error condition",
                f"    # result = {fn}(...invalid_input...)",
                f"    # assert result == {default_str}",
                "",
            ]
            return "\n".join(lines)

    return None


# ── Strategy 4: I/O Stubs ───────────────────────────────────────────────


def _generate_io_stub(
    func: ast.FunctionDef | ast.AsyncFunctionDef,
    module_path: str,
) -> str | None:
    """Generate executable mock-based test for I/O-heavy functions.

    Three I/O patterns get runnable tests:
    1. subprocess.run/call/check_output → @patch("subprocess.run")
    2. requests.get/post → @patch("requests.get")
    3. open/read/write → tmp_path fixture

    Other I/O patterns fall back to TODO stubs (smtplib, socket, etc.).

    Generated code is syntactically valid Python — pytest discovers
    and runs it (all tests pass trivially via ``pass``). The TODO
    comments guide the developer to fill in real args/assertions.
    """
    io_calls: list[str] = []

    for node in ast.walk(func):
        if not isinstance(node, ast.Call):
            continue

        call_name = _get_call_name(node)
        if call_name and _is_io_call(call_name):
            io_calls.append(call_name)

    if not io_calls:
        return None

    fn = func.name
    unique_calls = sorted(set(io_calls))

    # Classify I/O patterns
    has_subprocess = any(
        "subprocess" in c or c in ("run", "call", "check_output", "check_call", "Popen")
        for c in unique_calls
    )
    has_http = any(
        any(m in c for m in ("get", "post", "put", "delete", "patch", "request"))
        for c in unique_calls
        if "subprocess" not in c
    )
    has_file_io = any(
        c in ("open",) or c.endswith(".read") or c.endswith(".write")
        for c in unique_calls
    )

    # Check if we can generate executable tests for any pattern
    parts: list[str] = []

    if has_subprocess:
        parts.append(_generate_subprocess_mock(fn, module_path))

    if has_http:
        # Determine the specific HTTP method
        http_method = "get"
        for c in unique_calls:
            for m in ("post", "put", "delete", "patch"):
                if m in c:
                    http_method = m
                    break
        parts.append(_generate_http_mock(fn, module_path, http_method))

    if has_file_io:
        parts.append(_generate_file_io_mock(fn, module_path))

    # Fallback: unrecognized I/O patterns get TODO stubs
    if not parts:
        lines = [
            f"# TODO: Mock-based contract for {fn}",
            f"# Detected I/O: {', '.join(unique_calls)}",
        ]
        for call in unique_calls[:3]:
            lines.append(f"# Suggested: mock {call} and assert return handling")
        lines.append("")
        return "\n".join(lines)

    return "\n\n".join(parts)


def _generate_subprocess_mock(fn: str, module_path: str) -> str:
    """Generate executable subprocess mock test."""
    import_line = f"# from {module_path} import {fn}" if module_path else ""
    lines = [
        f"def test_{fn}_subprocess() -> None:",
        f'    """Contract: {fn} handles subprocess result."""',
        "    from unittest.mock import MagicMock, patch",
        "",
        "    mock_result = MagicMock()",
        "    mock_result.returncode = 0",
        '    mock_result.stdout = b""',
        '    mock_result.stderr = b""',
        '    with patch("subprocess.run", return_value=mock_result):',
        f"        pass  # TODO: call {fn} with valid args and assert result",
        "",
    ]
    if import_line:
        lines.insert(0, import_line)
    return "\n".join(lines)


def _generate_http_mock(fn: str, module_path: str, method: str = "get") -> str:
    """Generate executable HTTP requests mock test."""
    import_line = f"# from {module_path} import {fn}" if module_path else ""
    lines = [
        f"def test_{fn}_http() -> None:",
        f'    """Contract: {fn} handles HTTP response."""',
        "    from unittest.mock import MagicMock, patch",
        "",
        "    mock_resp = MagicMock()",
        "    mock_resp.status_code = 200",
        "    mock_resp.json.return_value = {}",
        '    mock_resp.text = ""',
        f'    with patch("requests.{method}", return_value=mock_resp):',
        f"        pass  # TODO: call {fn} with valid args and assert result",
        "",
    ]
    if import_line:
        lines.insert(0, import_line)
    return "\n".join(lines)


def _generate_file_io_mock(fn: str, module_path: str) -> str:
    """Generate executable file I/O mock test using tmp_path."""
    import_line = f"# from {module_path} import {fn}" if module_path else ""
    lines = [
        f"def test_{fn}_file_io(tmp_path) -> None:",
        f'    """Contract: {fn} handles file I/O."""',
        '    test_file = tmp_path / "test_input.txt"',
        '    test_file.write_text("test content")',
        f"    # TODO: call {fn}(str(test_file)) and assert result",
        "    pass",
        "",
    ]
    if import_line:
        lines.insert(0, import_line)
    return "\n".join(lines)


# ── Helpers ──────────────────────────────────────────────────────────────


def _annotation_to_str(node: ast.expr) -> str | None:
    """Convert an AST annotation node to a string."""
    if isinstance(node, ast.Constant):
        return str(node.value)
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        value = _annotation_to_str(node.value)
        return f"{value}.{node.attr}" if value else node.attr
    if isinstance(node, ast.Subscript):
        base = _annotation_to_str(node.value)
        if isinstance(node.slice, ast.Tuple):
            args = ", ".join(_annotation_to_str(e) or "Any" for e in node.slice.elts)
            return f"{base}[{args}]" if base else None
        else:
            arg = _annotation_to_str(node.slice)
            return f"{base}[{arg}]" if base else None
    if isinstance(node, ast.BinOp) and isinstance(node.op, ast.BitOr):
        # Union type: X | Y
        left = _annotation_to_str(node.left)
        right = _annotation_to_str(node.right)
        if left and right:
            return f"{left} | {right}"
    return None


def _annotation_to_isinstance(type_str: str) -> str | None:
    """Map a type annotation string to an isinstance-compatible type."""
    mapping = {
        "str": "str",
        "int": "int",
        "float": "(int, float)",
        "bool": "bool",
        "list": "list",
        "dict": "dict",
        "set": "set",
        "tuple": "tuple",
        "bytes": "bytes",
    }
    # Handle simple types
    base = type_str.split("[")[0].strip()
    return mapping.get(base)


def _value_to_str(node: ast.expr) -> str | None:
    """Convert a simple AST value to its string representation."""
    if isinstance(node, ast.Constant):
        return repr(node.value)
    if isinstance(node, ast.List) and len(node.elts) == 0:
        return "[]"
    if isinstance(node, ast.Dict) and len(node.keys) == 0:
        return "{}"
    if isinstance(node, ast.Tuple) and len(node.elts) == 0:
        return "()"
    if isinstance(node, ast.NameConstant):  # Python 3.7 compat
        return repr(node.value)
    return None


def _make_args_placeholder(func: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    """Build a placeholder argument string for a function call."""
    args = []
    for arg in func.args.args:
        if arg.arg == "self":
            continue
        args.append("...")
    return ", ".join(args)


def _get_call_name(node: ast.Call) -> str | None:
    """Extract the name of a function call."""
    if isinstance(node.func, ast.Name):
        return node.func.id
    if isinstance(node.func, ast.Attribute):
        if isinstance(node.func.value, ast.Name):
            return f"{node.func.value.id}.{node.func.attr}"
        return node.func.attr
    return None


def _is_io_call(call_name: str) -> bool:
    """Check if a call name indicates I/O."""
    parts = call_name.split(".")
    # Check module-level: subprocess.run, os.makedirs, etc.
    if parts[0] in _IO_MODULES:
        return True
    # Check function-level: open(), run(), etc.
    if len(parts) == 1 and parts[0] in _IO_FUNCTION_NAMES:
        return True
    # Check method-level: x.read(), x.write(), etc.
    if len(parts) >= 2 and parts[-1] in _IO_FUNCTION_NAMES:
        return True
    return False


def _compute_import_path(filepath: str, project_root: str) -> str:
    """Compute Python import path for a source file."""
    if not project_root:
        return os.path.splitext(os.path.basename(filepath))[0]
    try:
        rel = os.path.relpath(filepath, project_root)
        parts = os.path.splitext(rel)[0].split(os.sep)
        parts = [p for p in parts if p != "__init__"]
        return ".".join(parts)
    except ValueError:
        return os.path.splitext(os.path.basename(filepath))[0]
