"""HTML rendering helpers for the pages publisher.

Contains: _render_page, _asset_prefix, _build_sidebar, _build_prev_next,
_MdParser, _md_to_html, _inline_format.
"""

from __future__ import annotations

import html
import re
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from .composer import ComposedPage
    from .manifest import WikiManifest, WikiPage


def _page_slug(name: str) -> str:
    """Convert a page name/id to a URL slug."""
    return name.lower().replace(" ", "-")


def _render_page(
    title: str,
    site_title: str,
    content_html: str,
    sidebar_html: str,
    prev_next_html: str,
    active_page: str,
    description: str,
    base_url: str,
    slug: str,
) -> str:
    """Render a full HTML page."""
    base = base_url.rstrip("/")
    canonical = f"{base}/" if slug == "home" or active_page.lower() == "home" else f"{base}/{slug}/"
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{html.escape(title)} — {html.escape(site_title)}</title>
  <meta name="description" content="{html.escape(description)}">
  <meta name="generator" content="LintGate Wiki Publisher">
  <link rel="canonical" href="{canonical}">
  <link rel="stylesheet" href="{_asset_prefix(active_page)}style.css">
</head>
<body>
  <header class="site-header">
    <button class="sidebar-toggle" aria-label="Toggle sidebar">&#9776;</button>
    <a class="site-title" href="{_asset_prefix(active_page)}">{html.escape(site_title)}</a>
    <button class="theme-toggle" aria-label="Toggle dark mode" title="Toggle dark mode">&#9790;</button>
  </header>
  <div class="layout">
    <nav class="sidebar" role="navigation" aria-label="Wiki navigation">
      <div class="sidebar-header">
        <a href="{_asset_prefix(active_page)}">{html.escape(site_title)}</a>
      </div>
      {sidebar_html}
    </nav>
    <main class="content" role="main">
      <article>
        {content_html}
      </article>
      {prev_next_html}
    </main>
  </div>
  <footer class="site-footer">
    <p>Generated by <a href="https://github.com/rohanvinaik/lintgate">LintGate</a></p>
  </footer>
  <script src="{_asset_prefix(active_page)}script.js"></script>
</body>
</html>"""


def _asset_prefix(page_name: str) -> str:
    """Return relative path prefix for assets (../ for subpages, ./ for home)."""
    if page_name.lower() == "home":
        return "./"
    return "../"


def _build_sidebar(
    manifest: WikiManifest,
    composed: list[ComposedPage],
    is_root: bool = False,
) -> str:
    """Build sidebar HTML grouped by rail (or pillar if no rails).

    Args:
        is_root: True when rendering the Home/root page (links use ./ prefix).
    """
    prefix = "./" if is_root else "../"
    lines: list[str] = []
    composed_names = {p.name for p in composed}

    rails = manifest.rails
    if rails:
        for rail in rails:
            rail_pages = manifest.pages_by_rail(rail)
            if not rail_pages:
                continue
            label = manifest.rail_display_name(rail)
            lines.append('<div class="sidebar-group">')
            lines.append(f"  <h3>{html.escape(label)}</h3>")
            lines.append("  <ul>")
            for wp in rail_pages:
                if wp.name in composed_names:
                    slug = _page_slug(wp.name)
                    lines.append(
                        f'    <li data-page="{html.escape(wp.name)}">'
                        f'<a href="{prefix}{slug}/">{html.escape(wp.title)}</a></li>'
                    )
            lines.append("  </ul>")
            lines.append("</div>")

    # Pages without rails, grouped by pillar
    no_rail = [p for p in manifest.pages if not p.rail]
    if no_rail:
        seen_pillars: list[str] = []
        for page in no_rail:
            if page.pillar and page.pillar not in seen_pillars:
                seen_pillars.append(page.pillar)
        for pillar in seen_pillars:
            pillar_pages = [p for p in no_rail if p.pillar == pillar]
            pillar_pages.sort(key=lambda p: p.order)
            lines.append('<div class="sidebar-group">')
            lines.append(f"  <h3>{html.escape(pillar.title())}</h3>")
            lines.append("  <ul>")
            for wp in pillar_pages:
                if wp.name in composed_names:
                    slug = _page_slug(wp.name)
                    lines.append(
                        f'    <li data-page="{html.escape(wp.name)}">'
                        f'<a href="{prefix}{slug}/">{html.escape(wp.title)}</a></li>'
                    )
            lines.append("  </ul>")
            lines.append("</div>")

    return "\n".join(lines)


def _build_prev_next(
    prev_p: WikiPage | None,
    next_p: WikiPage | None,
    is_root: bool,
) -> str:
    """Build prev/next navigation HTML."""
    if not prev_p and not next_p:
        return ""

    prefix = "./" if is_root else "../"
    parts: list[str] = ['<nav class="prev-next" aria-label="Page navigation">']
    if prev_p:
        slug = _page_slug(prev_p.name)
        parts.append(
            f'  <a class="prev" href="{prefix}{slug}/">&larr; {html.escape(prev_p.title)}</a>'
        )
    else:
        parts.append('  <span class="prev"></span>')
    if next_p:
        slug = _page_slug(next_p.name)
        parts.append(
            f'  <a class="next" href="{prefix}{slug}/">{html.escape(next_p.title)} &rarr;</a>'
        )
    else:
        parts.append('  <span class="next"></span>')
    parts.append("</nav>")
    return "\n".join(parts)


class _MdParser:
    """Stateful line-by-line markdown-to-HTML converter."""

    def __init__(self) -> None:
        self.parts: list[str] = []
        self.in_code_block: bool = False
        self.in_list: bool = False
        self.in_table: bool = False
        self.paragraph_lines: list[str] = []

    def _flush_paragraph(self) -> None:
        if self.paragraph_lines:
            text = _inline_format(" ".join(self.paragraph_lines))
            self.parts.append(f"<p>{text}</p>")
            self.paragraph_lines.clear()

    def _flush_list(self) -> None:
        if self.in_list:
            self.parts.append("</ul>")
            self.in_list = False

    def _flush_table(self) -> None:
        if self.in_table:
            self.parts.append("</tbody></table>")
            self.in_table = False

    def _flush_all(self) -> None:
        self._flush_paragraph()
        self._flush_list()
        self._flush_table()

    def _handle_code_fence(self, line: str) -> None:
        if self.in_code_block:
            self.parts.append("</code></pre>")
            self.in_code_block = False
        else:
            self._flush_all()
            lang = line[3:].strip()
            cls = f' class="language-{html.escape(lang)}"' if lang else ""
            self.parts.append(f"<pre><code{cls}>")
            self.in_code_block = True

    def _handle_heading(self, match: re.Match[str]) -> None:
        self._flush_all()
        level = len(match.group(1))
        text = _inline_format(match.group(2))
        anchor = re.sub(r"[^a-z0-9]+", "-", match.group(2).lower()).strip("-")
        self.parts.append(f'<h{level} id="{anchor}">{text}</h{level}>')

    def _handle_table_row(self, stripped: str) -> bool:
        """Handle a table row. Returns True if the line was consumed."""
        self._flush_paragraph()
        self._flush_list()
        cells = [c.strip() for c in stripped.strip("|").split("|")]
        if all(re.match(r"^[-:]+$", c) for c in cells if c):
            return True  # separator row — skip
        if not self.in_table:
            self.parts.append("<table><tbody>")
            self.in_table = True
        row_html = "".join(f"<td>{_inline_format(c)}</td>" for c in cells)
        self.parts.append(f"<tr>{row_html}</tr>")
        return True

    def _handle_list_item(self, match: re.Match[str]) -> None:
        self._flush_paragraph()
        self._flush_table()
        if not self.in_list:
            self.parts.append("<ul>")
            self.in_list = True
        self.parts.append(f"<li>{_inline_format(match.group(1))}</li>")

    def feed(self, line: str) -> None:
        """Process a single line of markdown."""
        if line.startswith("```"):
            self._handle_code_fence(line)
            return
        if self.in_code_block:
            self.parts.append(html.escape(line))
            return

        stripped = line.strip()
        if not stripped:
            self._flush_all()
            return
        if stripped in ("---", "***", "___"):
            self._flush_all()
            self.parts.append("<hr>")
            return

        heading_match = re.match(r"^(#{1,6})\s+(.+)$", line)
        if heading_match:
            self._handle_heading(heading_match)
            return
        if stripped.startswith("|"):
            self._handle_table_row(stripped)
            return
        list_match = re.match(r"^[-*+]\s+(.+)$", stripped)
        if list_match:
            self._handle_list_item(list_match)
            return

        self._flush_list()
        self._flush_table()
        self.paragraph_lines.append(stripped)

    def finish(self) -> str:
        self._flush_all()
        if self.in_code_block:
            self.parts.append("</code></pre>")
        return "\n".join(self.parts)


def _md_to_html(text: str, link_fn: Any = None) -> str:
    """Minimal markdown-to-HTML conversion.

    Handles headings, paragraphs, lists, code blocks, bold, italic, links,
    tables, and horizontal rules. Not a full markdown parser — sufficient
    for wiki pages that follow our chapter grammar.
    """
    lines = [
        line for line in text.split("\n") if not line.strip().startswith("<!-- LINTGATE_WIKI:")
    ]
    parser = _MdParser()
    for line in lines:
        parser.feed(line)
    return parser.finish()


def _inline_format(text: str) -> str:
    """Apply inline markdown formatting: bold, italic, code, links."""
    # Inline code (before bold/italic to avoid conflicts)
    text = re.sub(r"`([^`]+)`", r"<code>\1</code>", text)
    # Bold
    text = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", text)
    # Italic
    text = re.sub(r"\*([^*]+)\*", r"<em>\1</em>", text)
    # Links
    text = re.sub(
        r"\[([^\]]+)\]\(([^)]+)\)",
        r'<a href="\2">\1</a>',
        text,
    )
    return text
