name = "Mutation_Theory"
version = "0.1.0"
defaultTargets = ["MutationTheory"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "f897ebcf72cd16f89ab4577d0c826cd14afaafc7"

[[lean_lib]]
name = "MutationTheory"

[[lean_exe]]
name = "mutation_theory"
root = "Main"
